<?php

use App\Modules\ProviderPayments\Http\Controllers\AcuerdoController;
use App\Modules\ProviderPayments\Http\Controllers\ApoyoAlzaController;
use App\Modules\ProviderPayments\Http\Controllers\BaseServicioController;
use App\Modules\ProviderPayments\Http\Controllers\ClientBranchMaintainerController;
use App\Modules\ProviderPayments\Http\Controllers\ClientMaintainerController;
use App\Modules\ProviderPayments\Http\Controllers\CostCenterKeyMaintainerController;
use App\Modules\ProviderPayments\Http\Controllers\CostCenterMaintainerController;
use App\Modules\ProviderPayments\Http\Controllers\CostCenterWeightRateMaintainerController;
use App\Modules\ProviderPayments\Http\Controllers\CourierMovementCompileController;
use App\Modules\ProviderPayments\Http\Controllers\CourierMovementImportController;
use App\Modules\ProviderPayments\Http\Controllers\CourierSpecialPaymentController;
use App\Modules\ProviderPayments\Http\Controllers\CoverageMaintainerController;
use App\Modules\ProviderPayments\Http\Controllers\ExternalShipmentController;
use App\Modules\ProviderPayments\Http\Controllers\OperationalMasterMaintainerController;
use App\Modules\ProviderPayments\Http\Controllers\ProviderPaymentsDashboardController;
use App\Modules\ProviderPayments\Http\Controllers\PurchaseOrderMailController;
use App\Modules\ProviderPayments\Http\Controllers\RutaCvController;
use App\Modules\ProviderPayments\Http\Controllers\ServiceTypeMaintainerController;
use App\Modules\ProviderPayments\Http\Controllers\VisitaDiariaController;
use App\Modules\ProviderPayments\Http\Controllers\WeightMaintainerController;
use Illuminate\Support\Facades\Route;

Route::prefix('pago-proveedores')
    ->name('provider-payments.')
    ->group(function (): void {
        Route::get('/', ProviderPaymentsDashboardController::class)->name('dashboard');
        Route::get('/movimientos', [ProviderPaymentsDashboardController::class, 'movements'])->name('movements.index');
        Route::delete('/movimientos/procesos', [ProviderPaymentsDashboardController::class, 'destroyProcess'])->name('movements.processes.destroy');
        Route::get('/carga-movimientos-courier', [CourierMovementImportController::class, 'index'])->name('courier-movements.upload');
        Route::view('/carga-movimientos-courier/lanas', 'provider-payments::courier-movements-upload', ['processType' => 'lanas', 'processTitle' => 'Courier Lanas'])->name('courier-movements.lanas');
        Route::view('/carga-movimientos-courier/retornos', 'provider-payments::courier-movements-upload', ['processType' => 'retornos', 'processTitle' => 'Courier Retornos'])->name('courier-movements.retornos');
        Route::get('/carga-movimientos-courier/especiales', [CourierSpecialPaymentController::class, 'index'])->name('courier-movements.especiales');
        Route::post('/carga-movimientos-courier/especiales', [CourierSpecialPaymentController::class, 'store'])->name('courier-movements.especiales.store');
        Route::put('/carga-movimientos-courier/especiales/{payment}', [CourierSpecialPaymentController::class, 'update'])->name('courier-movements.especiales.update');
        Route::put('/carga-movimientos-courier/especiales/{payment}/asociaciones', [CourierSpecialPaymentController::class, 'associate'])->name('courier-movements.especiales.associate');
        Route::put('/carga-movimientos-courier/especiales/asociaciones/guardar-todas', [CourierSpecialPaymentController::class, 'associatePage'])->name('courier-movements.especiales.associate-page');
        Route::post('/carga-movimientos-courier/especiales/finalizar', [CourierSpecialPaymentController::class, 'finalize'])->name('courier-movements.especiales.finalize');
        Route::post('/carga-movimientos-courier/especiales/{payment}/corregir-proveedor', [CourierSpecialPaymentController::class, 'correctProvider'])->name('courier-movements.especiales.correct-provider');
        Route::post('/carga-movimientos-courier/especiales/reabrir', [CourierSpecialPaymentController::class, 'reopen'])->name('courier-movements.especiales.reopen');
        Route::delete('/carga-movimientos-courier/especiales/{payment}', [CourierSpecialPaymentController::class, 'destroy'])->name('courier-movements.especiales.destroy');
        Route::get('/carga-movimientos-courier/rutas-cv', [RutaCvController::class, 'index'])->name('courier-movements.rutas-cv');
        Route::get('/carga-movimientos-courier/rutas-cv/plantilla', [RutaCvController::class, 'sourceRoutes'])->name('courier-movements.rutas-cv.source-routes');
        Route::post('/carga-movimientos-courier/rutas-cv/cargar', [RutaCvController::class, 'import'])->name('courier-movements.rutas-cv.import');
        Route::post('/carga-movimientos-courier/rutas-cv/generar', [RutaCvController::class, 'generate'])->name('courier-movements.rutas-cv.generate');
        Route::post('/carga-movimientos-courier/rutas-cv/guardar', [RutaCvController::class, 'update'])->name('courier-movements.rutas-cv.update');
        Route::post('/carga-movimientos-courier/rutas-cv/cerrar', [RutaCvController::class, 'close'])->name('courier-movements.rutas-cv.close');
        Route::post('/carga-movimientos-courier/rutas-cv/reabrir', [RutaCvController::class, 'reopen'])->name('courier-movements.rutas-cv.reopen');
        Route::post('/carga-movimientos-courier/rutas-cv/nueva', [RutaCvController::class, 'store'])->name('courier-movements.rutas-cv.store');
        Route::post('/carga-movimientos-courier/rutas-cv/frecuencias', [RutaCvController::class, 'storeFrequency'])->name('courier-movements.rutas-cv.frequencies.store');
        Route::get('/carga-movimientos-courier/servicios', [BaseServicioController::class, 'index'])->name('courier-movements.servicios');
        Route::post('/carga-movimientos-courier/servicios/cargar', [BaseServicioController::class, 'store'])->name('courier-movements.servicios.store');
        Route::put('/carga-movimientos-courier/servicios/asociaciones', [BaseServicioController::class, 'associatePage'])->name('courier-movements.servicios.associate-page');
        Route::post('/carga-movimientos-courier/servicios/cerrar', [BaseServicioController::class, 'close'])->name('courier-movements.servicios.close');
        Route::post('/carga-movimientos-courier/servicios/reabrir', [BaseServicioController::class, 'reopen'])->name('courier-movements.servicios.reopen');
        Route::get('/carga-movimientos-courier/acuerdos', [AcuerdoController::class, 'index'])->name('courier-movements.acuerdos');
        Route::post('/carga-movimientos-courier/acuerdos/cargar', [AcuerdoController::class, 'import'])->name('courier-movements.acuerdos.import');
        Route::post('/carga-movimientos-courier/acuerdos/generar', [AcuerdoController::class, 'generate'])->name('courier-movements.acuerdos.generate');
        Route::post('/carga-movimientos-courier/acuerdos/calendario', [AcuerdoController::class, 'calendar'])->name('courier-movements.acuerdos.calendar');
        Route::post('/carga-movimientos-courier/acuerdos/calendario/desbloquear', [AcuerdoController::class, 'unlockCalendar'])->name('courier-movements.acuerdos.calendar.unlock');
        Route::post('/carga-movimientos-courier/acuerdos/regla', [AcuerdoController::class, 'rule'])->name('courier-movements.acuerdos.rule');
        Route::post('/carga-movimientos-courier/acuerdos/guardar', [AcuerdoController::class, 'updateRows'])->name('courier-movements.acuerdos.update');
        Route::post('/carga-movimientos-courier/acuerdos/nuevo', [AcuerdoController::class, 'storeRow'])->name('courier-movements.acuerdos.store');
        Route::post('/carga-movimientos-courier/acuerdos/cerrar', [AcuerdoController::class, 'close'])->name('courier-movements.acuerdos.close');
        Route::post('/carga-movimientos-courier/acuerdos/reabrir', [AcuerdoController::class, 'reopen'])->name('courier-movements.acuerdos.reopen');
        Route::get('/carga-movimientos-courier/apoyo-alza', [ApoyoAlzaController::class, 'index'])->name('courier-movements.apoyo-alza');
        Route::post('/carga-movimientos-courier/apoyo-alza/cargar', [ApoyoAlzaController::class, 'import'])->name('courier-movements.apoyo-alza.import');
        Route::post('/carga-movimientos-courier/apoyo-alza/recalcular', [ApoyoAlzaController::class, 'recalculate'])->name('courier-movements.apoyo-alza.recalculate');
        Route::post('/carga-movimientos-courier/apoyo-alza/guardar', [ApoyoAlzaController::class, 'update'])->name('courier-movements.apoyo-alza.update');
        Route::post('/carga-movimientos-courier/apoyo-alza/cerrar', [ApoyoAlzaController::class, 'close'])->name('courier-movements.apoyo-alza.close');
        Route::post('/carga-movimientos-courier/apoyo-alza/reabrir', [ApoyoAlzaController::class, 'reopen'])->name('courier-movements.apoyo-alza.reopen');
        Route::get('/carga-movimientos-courier/visitas-diarias', [VisitaDiariaController::class, 'index'])->name('courier-movements.visitas');
        Route::get('/carga-movimientos-courier/envios-externos', [ExternalShipmentController::class, 'index'])->name('courier-movements.externos');
        Route::post('/carga-movimientos-courier/envios-externos/cargar', [ExternalShipmentController::class, 'import'])->name('courier-movements.externos.import');
        Route::get('/carga-movimientos-courier/envios-externos/pendientes/{token}.xlsx', [ExternalShipmentController::class, 'downloadIssueReport'])
            ->whereUuid('token')->name('courier-movements.externos.issues');
        Route::get('/carga-movimientos-courier/envios-externos/ya-pagados-historico.xlsx', [ExternalShipmentController::class, 'downloadExistingPaidReport'])
            ->name('courier-movements.externos.paid-existing-report');
        Route::get('/carga-movimientos-courier/envios-externos/ya-pagados/{token}.xlsx', [ExternalShipmentController::class, 'downloadPaidReport'])
            ->whereUuid('token')->name('courier-movements.externos.paid-report');
        Route::post('/carga-movimientos-courier/visitas-diarias/cargar', [VisitaDiariaController::class, 'import'])->name('courier-movements.visitas.import');
        Route::post('/carga-movimientos-courier/visitas-diarias/generar', [VisitaDiariaController::class, 'generate'])->name('courier-movements.visitas.generate');
        Route::post('/carga-movimientos-courier/visitas-diarias/guardar', [VisitaDiariaController::class, 'update'])->name('courier-movements.visitas.update');
        Route::post('/carga-movimientos-courier/visitas-diarias/nueva', [VisitaDiariaController::class, 'store'])->name('courier-movements.visitas.store');
        Route::post('/carga-movimientos-courier/visitas-diarias/cerrar', [VisitaDiariaController::class, 'close'])->name('courier-movements.visitas.close');
        Route::post('/carga-movimientos-courier/visitas-diarias/reabrir', [VisitaDiariaController::class, 'reopen'])->name('courier-movements.visitas.reopen');
        Route::post('/carga-movimientos-courier/validar', [CourierMovementImportController::class, 'validateFile'])->name('courier-movements.validate');
        Route::post('/carga-movimientos-courier/no-cargar-coberturas', [CourierMovementImportController::class, 'excludeCoverages'])->name('courier-movements.exclude-coverages');
        Route::post('/carga-movimientos-courier/no-cargar-servicios', [CourierMovementImportController::class, 'excludeServices'])->name('courier-movements.exclude-services');
        Route::post('/carga-movimientos-courier/transformar-pesos', [WeightMaintainerController::class, 'storeReviewWeights'])->name('courier-movements.transform-weights');
        Route::get('/carga-movimientos-courier/errores.csv', [CourierMovementImportController::class, 'downloadErrors'])->name('courier-movements.errors.download');
        Route::get('/carga-movimientos-courier/ya-pagados/{token}.xlsx', [CourierMovementImportController::class, 'downloadPaidReport'])->name('courier-movements.paid-report.download');
        Route::post('/carga-movimientos-courier/cargar', [CourierMovementImportController::class, 'storeMovements'])->name('courier-movements.store');
        Route::get('/compilar-movimientos-courier', [CourierMovementCompileController::class, 'index'])->name('courier-movements.compile');
        Route::post('/compilar-movimientos-courier/cerrar-periodo', [CourierMovementCompileController::class, 'closePeriod'])->name('courier-movements.compile.close');
        Route::get('/compilar-movimientos-courier/consolidado.xlsx', [CourierMovementCompileController::class, 'exportConsolidated'])->name('courier-movements.compile.export');
        Route::get('/compilar-movimientos-courier/ordenes-de-compra', [CourierMovementCompileController::class, 'purchaseOrders'])->name('courier-movements.compile.purchase-orders');
        Route::get('/compilar-movimientos-courier/ordenes-de-compra/resumen.xlsx', [CourierMovementCompileController::class, 'purchaseOrdersSummaryExcel'])->name('courier-movements.compile.purchase-orders.summary-excel');
        Route::get('/compilar-movimientos-courier/ordenes-de-compra/correos', [PurchaseOrderMailController::class, 'index'])->name('courier-movements.compile.purchase-orders.mail');
        Route::post('/compilar-movimientos-courier/ordenes-de-compra/correos/configurar', [PurchaseOrderMailController::class, 'configure'])->name('courier-movements.compile.purchase-orders.mail.configure');
        Route::post('/compilar-movimientos-courier/ordenes-de-compra/correos/prueba', [PurchaseOrderMailController::class, 'test'])->name('courier-movements.compile.purchase-orders.mail.test');
        Route::post('/compilar-movimientos-courier/ordenes-de-compra/correos/confirmar', [PurchaseOrderMailController::class, 'confirm'])->name('courier-movements.compile.purchase-orders.mail.confirm');
        Route::post('/compilar-movimientos-courier/ordenes-de-compra/correos/enviar', [PurchaseOrderMailController::class, 'send'])->name('courier-movements.compile.purchase-orders.mail.send');
        Route::get('/compilar-movimientos-courier/ordenes-de-compra/{oc}.pdf', [CourierMovementCompileController::class, 'purchaseOrderPdf'])->where('oc', '[0-9]{10}')->name('courier-movements.compile.purchase-orders.pdf');
        Route::get('/compilar-movimientos-courier/ordenes-de-compra/{oc}.xlsx', [CourierMovementCompileController::class, 'purchaseOrderExcel'])->where('oc', '[0-9]{10}')->name('courier-movements.compile.purchase-orders.excel');
        Route::get('/compilar-movimientos-courier/trabajar', [CourierMovementCompileController::class, 'work'])->name('courier-movements.compile.work');
        Route::get('/compilar-movimientos-courier/trabajar/revisar-llaves-cc', [CourierMovementCompileController::class, 'reviewKeys'])->name('courier-movements.compile.keys.review');
        Route::post('/compilar-movimientos-courier/trabajar/guardar-llaves-cc', [CourierMovementCompileController::class, 'saveReviewedKeys'])->name('courier-movements.compile.keys.save');
        Route::post('/compilar-movimientos-courier/trabajar', [CourierMovementCompileController::class, 'compile'])->name('courier-movements.compile.store');
        Route::post('/compilar-movimientos-courier/trabajar/generar-llaves-cc', [CourierMovementCompileController::class, 'generateMissingKeys'])->name('courier-movements.compile.keys.generate');
        Route::delete('/compilar-movimientos-courier/procesos', [CourierMovementCompileController::class, 'destroyProcess'])->name('courier-movements.compile.destroy');
        Route::post('/compilar-movimientos-courier/trabajar/estados-no-pagar', [CourierMovementCompileController::class, 'markNonPayable'])->name('courier-movements.compile.non-payable.mark');
        Route::post('/compilar-movimientos-courier/trabajar/proveedor-interno', [CourierMovementCompileController::class, 'markInternalProvider'])->name('courier-movements.compile.internal-provider.mark');
        Route::post('/compilar-movimientos-courier/trabajar/asignar-pagos', [CourierMovementCompileController::class, 'assignPayments'])->name('courier-movements.compile.payments.assign');
        Route::post('/compilar-movimientos-courier/trabajar/actualizar-proveedores-4n', [CourierMovementCompileController::class, 'updateFourNorthProviders'])->name('courier-movements.compile.providers-4n.update');

        Route::get('/mantenedor/coberturas', [CoverageMaintainerController::class, 'create'])->name('maintainers.coberturas');
        Route::post('/mantenedor/coberturas', [CoverageMaintainerController::class, 'store'])->name('maintainers.coberturas.store');
        Route::put('/mantenedor/coberturas/{coverage}', [CoverageMaintainerController::class, 'update'])->name('maintainers.coberturas.update');
        Route::get('/mantenedor/clientes', [ClientMaintainerController::class, 'create'])->name('maintainers.clientes');
        Route::post('/mantenedor/clientes', [ClientMaintainerController::class, 'store'])->name('maintainers.clientes.store');
        Route::put('/mantenedor/clientes/{client}', [ClientMaintainerController::class, 'update'])->name('maintainers.clientes.update');
        Route::get('/mantenedor/sucursales', [ClientBranchMaintainerController::class, 'index'])->name('maintainers.sucursales');
        Route::post('/mantenedor/sucursales', [ClientBranchMaintainerController::class, 'store'])->name('maintainers.sucursales.store');
        Route::put('/mantenedor/sucursales/{branch}', [ClientBranchMaintainerController::class, 'update'])->name('maintainers.sucursales.update');
        Route::get('/mantenedor/servicios', [ServiceTypeMaintainerController::class, 'index'])->name('maintainers.servicios');
        Route::post('/mantenedor/servicios', [ServiceTypeMaintainerController::class, 'store'])->name('maintainers.servicios.store');
        Route::get('/mantenedor/centro-de-costos', [CostCenterMaintainerController::class, 'index'])->name('maintainers.centro-de-costos');
        Route::post('/mantenedor/centro-de-costos', [CostCenterMaintainerController::class, 'store'])->name('maintainers.centro-de-costos.store');
        Route::get('/mantenedor/tarifas-cc', [CostCenterWeightRateMaintainerController::class, 'index'])->name('maintainers.tarifas-cc');
        Route::post('/mantenedor/tarifas-cc', [CostCenterWeightRateMaintainerController::class, 'store'])->name('maintainers.tarifas-cc.store');
        Route::put('/mantenedor/tarifas-cc/{rate}', [CostCenterWeightRateMaintainerController::class, 'update'])->name('maintainers.tarifas-cc.update');
        Route::redirect('/mantenedor/pesos', '/pago-proveedores/mantenedor/pesos/transformados')->name('maintainers.pesos');
        Route::get('/mantenedor/pesos/transformados', [WeightMaintainerController::class, 'transformed'])->name('maintainers.pesos.transformados');
        Route::post('/mantenedor/pesos/transformados', [WeightMaintainerController::class, 'storeReal'])->name('maintainers.pesos.transformados.store');
        Route::put('/mantenedor/pesos/transformados/{weight}', [WeightMaintainerController::class, 'update'])->name('maintainers.pesos.transformados.update');
        Route::get('/mantenedor/pesos/reales', [WeightMaintainerController::class, 'real'])->name('maintainers.pesos.reales');
        Route::post('/mantenedor/pesos/reales/cargar', [WeightMaintainerController::class, 'importRealWeights'])->name('maintainers.pesos.reales.import');
        Route::post('/mantenedor/pesos/reales/sincronizar', [WeightMaintainerController::class, 'syncRealWeights'])->name('maintainers.pesos.reales.sync');
        Route::get('/mantenedor/proveedores', [OperationalMasterMaintainerController::class, 'providers'])->name('maintainers.proveedores');
        Route::post('/mantenedor/proveedores', [OperationalMasterMaintainerController::class, 'storeProvider'])->name('maintainers.proveedores.store');
        Route::put('/mantenedor/proveedores/{provider}', [OperationalMasterMaintainerController::class, 'updateProvider'])->name('maintainers.proveedores.update');
        Route::post('/mantenedor/proveedores/{provider}/nombre-archivo-oc', [OperationalMasterMaintainerController::class, 'saveProviderOcFilename'])->name('maintainers.proveedores.oc-filename');
        Route::get('/mantenedor/bancos', [OperationalMasterMaintainerController::class, 'banks'])->name('maintainers.bancos');
        Route::post('/mantenedor/bancos', [OperationalMasterMaintainerController::class, 'storeBank'])->name('maintainers.bancos.store');
        Route::put('/mantenedor/bancos/{banco}', [OperationalMasterMaintainerController::class, 'updateBank'])->name('maintainers.bancos.update');
        Route::post('/mantenedor/bancos/tipos-cuenta', [OperationalMasterMaintainerController::class, 'storeBankAccountType'])->name('maintainers.bancos.tipos-cuenta.store');
        Route::put('/mantenedor/bancos/tipos-cuenta/{accountType}', [OperationalMasterMaintainerController::class, 'updateBankAccountType'])->name('maintainers.bancos.tipos-cuenta.update');
        Route::get('/mantenedor/vehiculos', [OperationalMasterMaintainerController::class, 'vehicles'])->name('maintainers.vehiculos');
        Route::post('/mantenedor/vehiculos', [OperationalMasterMaintainerController::class, 'storeVehicle'])->name('maintainers.vehiculos.store');
        Route::put('/mantenedor/vehiculos/{vehicle}', [OperationalMasterMaintainerController::class, 'updateVehicle'])->name('maintainers.vehiculos.update');
        Route::get('/mantenedor/estados', [OperationalMasterMaintainerController::class, 'statuses'])->name('maintainers.estados');
        Route::post('/mantenedor/estados', [OperationalMasterMaintainerController::class, 'storeStatus'])->name('maintainers.estados.store');
        Route::put('/mantenedor/estados/{status}', [OperationalMasterMaintainerController::class, 'updateStatus'])->name('maintainers.estados.update');
        Route::get('/mantenedor/llave-centro-costos', [CostCenterKeyMaintainerController::class, 'create'])->name('maintainers.llave-centro-costos');
        Route::post('/mantenedor/llave-centro-costos', [CostCenterKeyMaintainerController::class, 'store'])->name('maintainers.llave-centro-costos.store');
        Route::post('/mantenedor/llave-centro-costos/nueva', [CostCenterKeyMaintainerController::class, 'storeManual'])->name('maintainers.llave-centro-costos.manual-store');
        Route::post('/mantenedor/llave-centro-costos/replicar-proveedor', [CostCenterKeyMaintainerController::class, 'replicateProvider'])->name('maintainers.llave-centro-costos.replicate-provider');
        Route::post('/mantenedor/llave-centro-costos/guardar-cambios', [CostCenterKeyMaintainerController::class, 'updateMany'])->name('maintainers.llave-centro-costos.update-many');
        Route::put('/mantenedor/llave-centro-costos/{key}', [CostCenterKeyMaintainerController::class, 'update'])->name('maintainers.llave-centro-costos.update');

    });

Route::get('/pago-proveedores/carga-movimientos-courier/revisar-parametros', [CourierMovementImportController::class, 'reviewParameters'])->name('provider-payments.courier-movements.review-parameters');
