@extends('portal.layout')
@section('content')
<header class="greeting"><h1>Hola, {{ explode(' ', trim(auth()->user()->name))[0] }} <span aria-hidden="true">👋</span></h1><p>Bienvenido a tu espacio de trabajo.</p></header>
@if(request()->attributes->get('portal_tenant')?->pivot?->role_code === 'driver')
<section class="card" style="margin-bottom:20px"><div class="card-heading"><span class="card-icon">@include('portal.icon',['icon'=>'truck'])</span><div><h2>Mi Ruta</h2><p class="muted">Revisa tus recorridos asignados y registra cada parada desde el celular.</p></div></div><a class="button" href="{{ route('operations.driver.index') }}">Abrir mi ruta de hoy</a></section>
@endif
<section class="card"><div class="card-heading"><span class="card-icon">@include('portal.icon',['icon'=>'clock'])</span><div><h2>Tu actividad</h2><p class="muted">Registro de utilización de tu cuenta</p></div></div><div class="stats"><div class="stat">Actividades de hoy <b>{{ $todayCount }}</b></div><div class="stat">Módulos visitados hoy <b>{{ $moduleCount }}</b></div></div><div class="section-line"><span>ÚLTIMOS MOVIMIENTOS</span><span>FECHA Y HORA</span></div>
@forelse($activities as $activity)<div class="activity"><span class="activity-mark">@include('portal.icon',['icon'=>'clock'])</span><div><strong>{{ $activity->action }}</strong><small>{{ $activity->module }}</small></div><time>{{ \Illuminate\Support\Carbon::parse($activity->created_at)->timezone('America/Santiago')->format('d/m/Y · H:i') }}</time></div>@empty<div class="empty">Aún no hay actividad registrada.<br>Tus accesos y acciones aparecerán aquí.</div>@endforelse
@if($activities->hasPages())<nav class="pagination" aria-label="Páginas de actividad"><span>@if($activities->previousPageUrl())<a href="{{ $activities->previousPageUrl() }}">Anterior</a>@endif</span><span>{{ $activities->currentPage() }} / {{ $activities->lastPage() }}</span><span>@if($activities->nextPageUrl())<a href="{{ $activities->nextPageUrl() }}">Siguiente</a>@endif</span></nav>@endif</section>
<div class="shortcuts">@if(auth()->user()->isProviderPaymentsAdministrator())<a class="button" href="{{ route('provider-payments.dashboard') }}">@include('portal.icon',['icon'=>'money']) Pago Proveedores</a>@endif<a class="button" href="{{ route('portal.profile') }}">@include('portal.icon',['icon'=>'user']) Mi cuenta</a></div><p class="footnote">{{ request()->attributes->get('portal_tenant')->name }} · 4N Logística</p>
@endsection
