@extends('operations::layout')
@section('title','Programación de salidas')
@section('content')
<h1>Salidas de agencias · Proceso #{{ $lot->id }}</h1><p class="intro">{{ $lot->name }} · {{ $lot->operation_date }}</p><p><a href="{{ route('operations.lots.show',$lot->id) }}">Volver a bultos e incidencias</a></p>
@if($blocked)<p class="warning">Hay {{ $blocked }} incidencias pendientes. Resuélvelas antes de programar salidas.</p>@endif
@if($missing->isNotEmpty())<div class="warning">Falta configurar el recorrido para: @foreach($missing as $coverage)<span>{{ $coverage->commune_name }} (#{{ $coverage->id }}){{ !$loop->last ? ', ' : '.' }}</span>@endforeach <a href="{{ route('operations.setup') }}">Configurar agencias</a></div>@endif
<section class="card"><h2>Marcar agencias que salen</h2><form method="POST" action="{{ route('operations.departures.store',$lot->id) }}">@csrf
<div class="ope-form"><label>Nombre de salida<input name="name" value="{{ old('name') }}" required maxlength="160" placeholder="Troncal Sur · salida 1"></label><label>Fecha<input type="date" name="departure_date" value="{{ old('departure_date',$lot->operation_date) }}" required></label></div>
<p class="note">Marca las agencias del mismo tramo, origen y destino. Las que no selecciones permanecen en reserva. Programa primero Troncal, luego Posta 1 y Posta 2.</p>
<div class="table-wrap"><table class="ope-table"><thead><tr><th>Sale</th><th>Tramo</th><th>Cobertura / Agencia</th><th>Troncal / Posta</th><th>Origen → Destino</th><th>Bultos</th><th>Peso kg</th><th>Estado</th></tr></thead><tbody>@forelse($configurations as $configuration)<tr><td><input aria-label="Seleccionar {{ $configuration->name }} {{ $configuration->role }}" type="checkbox" name="configuration_ids[]" value="{{ $configuration->id }}" @disabled($scheduled->contains($configuration->id) || $blocked) @checked(in_array($configuration->id,old('configuration_ids',[])))></td><td>{{ ['troncal'=>'Troncal','posta1'=>'Posta 1','posta2'=>'Posta 2'][$configuration->role] }}</td><td>{{ $configuration->commune_name }} · {{ $configuration->name }}</td><td>{{ $configuration->trunk_name }} / {{ $configuration->post_name }}</td><td>{{ $configuration->origin_name }} → {{ $configuration->destination_name }}</td><td>{{ $counts[$configuration->coverage_id]->count }}</td><td>{{ number_format((float)$counts[$configuration->coverage_id]->weight,3,',','.') }}</td><td><span class="ope-badge">{{ $scheduled->contains($configuration->id) ? 'Programada' : 'Reserva' }}</span></td></tr>@empty<tr><td colspan="8" class="ope-empty">No hay agencias configuradas con bultos en este proceso.</td></tr>@endforelse</tbody></table></div>
<div class="ope-actions"><button @disabled($blocked)>Programar salida seleccionada</button></div></form></section>
<h2>Salidas y revisión del supervisor</h2><div class="card table-wrap"><table class="ope-table"><thead><tr><th>Salida</th><th>Fecha / Tramo</th><th>Transporte</th><th>Estado</th><th></th></tr></thead><tbody>@forelse($departures as $departure)<tr><td>#{{ $departure->id }} · {{ $departure->name }}</td><td>{{ $departure->departure_date }} / {{ $departure->role }}</td><td>{{ $departure->plate ?: 'Sin patente' }} · {{ $departure->driver_name ?: 'Sin chofer' }}</td><td>{{ ['approved'=>'Aprobada','draft'=>'Pendiente supervisor','cancelled'=>'Cancelada'][$departure->status] }}</td><td><a href="{{ route('operations.departures.show',$departure->id) }}">Revisar salida y guía</a></td></tr>@empty<tr><td colspan="5" class="ope-empty">Selecciona las agencias para crear la primera salida.</td></tr>@endforelse</tbody></table></div>
@endsection
