@extends('operations::layout')
@section('title','Supervisor de salida')
@section('content')
<h1>Supervisor · Salida #{{ $departure->id }} · {{ $departure->name }}</h1><p class="intro">{{ $departure->departure_date }} · {{ $departure->role }} · Versión {{ $departure->version }} · {{ ['approved'=>'Aprobada','draft'=>'Pendiente de aprobación','cancelled'=>'Cancelada'][$departure->status] }}</p><p><a href="{{ route('operations.departures.index',$departure->lot_id) }}">Volver a salidas</a></p>
@php($supervisor=\App\Modules\Operations\Services\OperationAccess::supervisor(request()))
@if($supervisor && $departure->status==='draft')<section class="card"><h2>Chofer y patente de esta salida</h2><form method="POST" action="{{ route('operations.departures.assignment',$departure->id) }}" class="ope-form">@csrf @method('PUT')
<label>Patente<input name="plate" list="ope-vehicles" value="{{ old('plate',$departure->plate) }}" required maxlength="10" placeholder="ABCD12"><datalist id="ope-vehicles">@foreach($vehicles as $vehicle)<option value="{{ $vehicle->plate }}">@endforeach</datalist></label>
<label>Chofer<input name="driver_name" id="ope-driver" list="ope-drivers" value="{{ old('driver_name',$departure->driver_name) }}" required maxlength="160"><datalist id="ope-drivers">@foreach($drivers as $driver)<option value="{{ $driver->name }}" data-rut="{{ $driver->tax_id }}">@endforeach</datalist></label>
<label>RUT chofer<input name="driver_rut" id="ope-rut" value="{{ old('driver_rut',$departure->driver_rut) }}" required maxlength="15" placeholder="12345678-5"></label><button>Guardar transporte</button></form><p class="note">Puedes ingresar un chofer externo. Revisa su identidad y RUT antes de confirmar. Los datos quedan asociados a esta salida y fecha.</p></section>@endif
<h2>Vista previa de guía interna</h2>@include('operations::guide-content',['preview'=>$preview])
@if($supervisor && $departure->status==='draft')<form method="POST" action="{{ route('operations.departures.approve',$departure->id) }}" class="card ope-actions">@csrf<label><input type="checkbox" name="confirmed" value="1" required> Confirmo agencias, direcciones, chofer, RUT, patente, bultos y pesos.</label><button>Aprobar y guardar guía interna</button></form>@endif
@if($supervisor && $departure->status==='approved')<details class="card"><summary>Reabrir salida para corregir transporte</summary><p class="note">Se conserva la guía anterior y se requiere aprobar una nueva versión. Si hay postas posteriores aprobadas, reábralas primero.</p><form method="POST" action="{{ route('operations.departures.reopen',$departure->id) }}" class="ope-form">@csrf<label>Motivo<textarea name="reason" minlength="10" maxlength="1000" required></textarea></label><button>Reabrir salida</button></form></details>@endif
<h2>Guías y versiones</h2>
@if($supervisor && $departure->status === 'draft' && $guides->isEmpty())<details class="card"><summary>Cancelar programación de salida</summary><form method="POST" action="{{ route('operations.departures.cancel',$departure->id) }}" class="ope-form">@csrf<label>Motivo<textarea name="reason" minlength="10" maxlength="1000" required></textarea></label><button>Cancelar y devolver a reserva</button></form></details>@endif
@forelse($guides as $guide)<p><a href="{{ route('operations.guides.show',$guide->id) }}">Guía interna #{{ $guide->id }} · versión {{ $guide->version }}</a> · aprobada {{ $guide->created_at }}</p>@empty<p class="note">La guía se guarda al aprobar la salida.</p>@endforelse
<details class="card"><summary>Historial de la salida</summary>@foreach($audit as $event)<p>{{ $event->created_at }} · {{ $event->action }} · usuario #{{ $event->user_id }}</p><details><summary>Ver cambio</summary><pre>{{ $event->after }}</pre></details>@endforeach</details>
@endsection
@push('scripts')<script>const opeDriver=document.getElementById('ope-driver'); if(opeDriver){opeDriver.addEventListener('change',()=>{const options=[...document.querySelectorAll('#ope-drivers option')].filter(option=>option.value===opeDriver.value);if(options.length===1){document.getElementById('ope-rut').value=options[0].dataset.rut;}});}</script>@endpush
