<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>@yield('title', 'Operaciones') · 4N Logística</title><link rel="icon" href="{{ asset('favicon.svg') }}"><style>

        :root { --navy:#061f20; --ink:#102a2d; --muted:#60757a; --turquoise:#28c9c8; --turquoise-dark:#007f82; --turquoise-soft:#d9f5f4; --paper:#f4f7f7; --line:#d7e1e2; --white:#fff; }
        * { box-sizing:border-box; }
        [hidden] { display:none!important; }
        body { margin:0; min-height:100vh; background:var(--paper); color:var(--ink); font-family:system-ui,-apple-system,"Segoe UI",sans-serif; }
        .topbar { position:sticky; top:0; z-index:20; height:76px; display:flex; align-items:center; justify-content:space-between; padding:0 22px; background:var(--navy); color:#fff; }
        .brand { display:flex; align-items:center; gap:12px; color:#fff; text-decoration:none; }
        .brand-mark { width:44px; height:44px; display:grid; place-items:center; border-radius:11px; background:var(--turquoise); color:var(--navy); font-size:20px; font-weight:900; }
        .brand strong,.brand small { display:block; }.brand strong{font-size:16px}.brand small{margin-top:2px;color:#c9eeee;font-size:12px}.topbar-right{display:flex;align-items:center;gap:12px;margin-left:auto;min-width:0}.user-area{font-size:13px;white-space:nowrap}.user-area a{margin-left:18px;color:var(--turquoise);text-decoration:none}
        .shell { display:grid; grid-template-columns:222px minmax(0,1fr); min-height:calc(100vh - 76px); }
        .sidebar { padding:23px 9px; border-right:1px solid var(--line); background:#fff; }
        .nav-link,.nav-summary { display:flex; align-items:center; gap:10px; width:100%; padding:12px 15px; border-radius:9px; color:#26474c; cursor:pointer; font-size:14px; font-weight:700; text-decoration:none; }
        .sidebar .icon{width:18px;height:18px;flex-shrink:0;fill:none;stroke:currentColor;stroke-width:1.7;stroke-linecap:round;stroke-linejoin:round}
        .nav-text{flex:1;min-width:0}
        .nav-link:hover,.nav-summary:hover,.nav-link.active,.nav-summary.active { background:var(--turquoise-soft); color:#006d70; }
        .nav-summary { list-style:none; }.nav-summary::-webkit-details-marker{display:none}.nav-summary::after{margin-left:auto;content:'⌄';color:var(--turquoise-dark)}details[open]>.nav-summary::after{content:'⌃'}
        .subnav a { display:block; padding:9px 15px 9px 43px; color:#53696d; font-size:13px; text-decoration:none; }.subnav a:hover,.subnav a.active{color:var(--turquoise-dark);font-weight:800}
        .content { min-width:0; padding:28px clamp(20px,4vw,64px) 48px; }
        .eyebrow { margin:0 0 8px; color:var(--turquoise-dark); font-size:11px; font-weight:900; letter-spacing:1.6px; text-transform:uppercase; }
        .page-heading{display:flex;align-items:center;gap:10px;max-width:100%;margin:0 0 10px;overflow-x:auto;white-space:nowrap;scrollbar-width:thin}
        .page-heading .back,.page-heading .eyebrow{flex:none;margin:0;font-size:12px;line-height:1.4;letter-spacing:0;text-transform:none}
        .page-heading .eyebrow{font-weight:750}
        .page-heading h1{flex:none;margin:0;font-size:18px;line-height:1.4;font-weight:800}
        .page-heading .eyebrow::before,.page-heading h1::before{content:'–';padding-right:10px;color:var(--muted);font-weight:400}
        .page-heading .compile-period{margin-left:auto}
        @media(max-width:760px){.page-heading h1{font-size:16px}.page-heading{gap:7px}.page-heading .eyebrow::before,.page-heading h1::before{padding-right:7px}}
        h1 { margin:0; color:#071b1d; font-size:26px; line-height:1.2; } h2{color:#071b1d;font-size:20px}h3{font-size:16px}.intro{margin:7px 0 20px;color:var(--muted)}
        a{color:var(--turquoise-dark)}.back{display:inline-block;margin-bottom:18px;font-size:14px}
        .card,.box,details.review-group { background:#fff; border:1px solid var(--line); border-radius:11px; box-shadow:0 1px 2px rgb(6 31 32 / 3%); }
        .card{padding:18px}.button,button{display:inline-flex;align-items:center;justify-content:center;gap:5px;min-height:36px;padding:8px 13px;border:0;border-radius:7px;background:var(--turquoise-dark);color:#fff;cursor:pointer;font-size:13px;line-height:1.3;font-weight:750;text-decoration:none}.button:hover,button:hover{background:#00696c}button:disabled{opacity:.6}
        input:not([type=checkbox]):not([type=radio]):not([type=hidden]),select,textarea{max-width:100%;font-size:13px}select,input:not([type=checkbox]):not([type=radio]):not([type=hidden]){min-height:36px}
        table{width:100%;border-collapse:collapse}th,td{padding:9px 12px;border-bottom:1px solid #e7eeee;text-align:left}th{background:#effafa;color:#087477;font-size:11px;text-transform:uppercase}td:last-child,th:last-child{text-align:right}tr:last-child td{border-bottom:0}.table-wrap{overflow:auto}
        .note{color:var(--muted);font-size:14px}.warning{padding:15px;border-left:4px solid #db9f34;background:#fff6e4}.progress-track{height:9px;overflow:hidden;border-radius:99px;background:#dcecec}.progress-bar{width:35%;height:100%;background:var(--turquoise);animation:loading 1.2s ease-in-out infinite}@keyframes loading{from{transform:translateX(-110%)}to{transform:translateX(310%)}}progress{width:100%;accent-color:var(--turquoise-dark)}
        .pp-pager{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:16px 0;font-size:14px}.pp-pager-current,.pp-pager-button{display:inline-flex;align-items:center;min-height:38px;padding:8px 12px;border:1px solid var(--line);border-radius:7px;background:#fff;white-space:nowrap}.pp-pager-actions{display:flex;gap:8px;margin-left:auto}.pp-pager-button{color:var(--turquoise-dark);text-decoration:none}.pp-pager-button:hover{border-color:var(--turquoise-dark);background:var(--turquoise-soft)}.pp-pager-button.is-disabled{color:var(--muted);opacity:.7;cursor:default}.pp-pager-button.is-disabled:hover{border-color:var(--line);background:#fff}@media(max-width:480px){.pp-pager{flex-wrap:wrap}.pp-pager-actions{margin-left:0}}
        .master-tools{display:grid;grid-template-columns:minmax(240px,1fr) 220px auto;gap:10px;align-items:end;margin:0 0 22px;padding:16px;border:1px solid var(--line);border-radius:12px;background:#fff}.master-tools label{display:grid;gap:6px;color:var(--muted);font-size:12px;font-weight:800;text-transform:uppercase}.master-tools input,.master-tools select{width:100%;padding:10px 12px;border:1px solid var(--line);border-radius:8px;background:#fff;color:var(--ink)}.master-results{padding:10px 0;color:var(--muted);font-size:13px;white-space:nowrap}.new-record-toggle{margin:0 0 18px}.creator-open{display:block!important;grid-column:1/-1}
        @media(max-width:760px){.topbar{height:auto;min-height:70px}.user-area{display:none}.shell{display:block}.sidebar{border-right:0;border-bottom:1px solid var(--line)}.content{padding:26px 18px}.sidebar>.nav-link{display:inline-flex;width:auto;vertical-align:top}.sidebar>details{display:inline-block;width:auto;vertical-align:top}.subnav{position:absolute;z-index:10;background:#fff;border:1px solid var(--line);border-radius:8px;padding:5px}.master-tools{grid-template-columns:1fr}}

.ope-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:16px;margin:18px 0}.ope-form{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px;align-items:end}.ope-form label{display:grid;gap:6px;font-size:13px;font-weight:650}.ope-form input,.ope-form select,.ope-form textarea{width:100%;padding:9px;border:1px solid var(--line);border-radius:7px;background:#fff}.ope-form label.check{display:flex;align-items:center}.ope-form label.check input{width:auto}.ope-full{grid-column:1/-1}.ope-actions{display:flex;flex-wrap:wrap;gap:10px;align-items:center;margin:16px 0}.ope-stat{font-size:28px;font-weight:800;display:block}.ope-table td{font-size:13px}.ope-badge{display:inline-block;padding:4px 9px;border-radius:5px;background:var(--turquoise-soft);font-size:12px}.ope-error{background:#fff3e1;color:#8b4e00}.success{padding:14px;background:var(--turquoise-soft);margin-bottom:16px;border-radius:7px}.error{padding:14px;background:#fff0ef;color:#9c2929;margin-bottom:16px;border-radius:7px}details.card{margin:12px 0}details.card summary{cursor:pointer;font-weight:700}.ope-form textarea{min-height:70px}.ope-muted{color:var(--muted)}pre{white-space:pre-wrap;word-break:break-word;font-size:12px}.ope-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:18px}.ope-heading h1{font-size:22px}.ope-empty{padding:30px;text-align:center;color:var(--muted)}@media print{.topbar,.sidebar,.ope-actions,.success,.error,.no-print{display:none!important}.shell{display:block}.content{padding:0}.card{box-shadow:none;border:0}body{background:white}th{background:#eee}}
.ope-transport-dialog{width:min(850px,calc(100vw - 30px));max-height:calc(100vh - 40px);padding:24px;border:1px solid var(--line);border-radius:12px;box-shadow:0 20px 60px rgb(0 0 0 / 22%);color:var(--ink)}.ope-transport-dialog::backdrop{background:rgb(2 23 26 / 58%)}.ope-transport-dialog-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.ope-transport-dialog-head h2{margin:0 0 8px}.ope-dialog-close{min-width:36px;font-size:22px;padding:4px 9px}.ope-secondary-button{background:#e8eeee;color:var(--ink)}.ope-secondary-button:hover{background:#d7e2e3}.ope-transport-dialog .ope-actions{margin:4px 0 0}.ope-transport-dialog .note:last-child{margin-bottom:0}
.ope-list-trigger{min-height:28px;padding:2px 7px;border:0;background:transparent;color:var(--turquoise-dark);white-space:nowrap;font-weight:800}.ope-list-trigger:hover{background:var(--turquoise-soft);color:#00696c}.ope-list-trigger span{font-size:16px}.ope-coverages-dialog{width:min(1150px,calc(100vw - 30px))}.ope-coverages-dialog .table-wrap{max-height:min(62vh,650px);overflow:auto}.ope-coverages-dialog th{position:sticky;top:0}.ope-coverages-dialog .note{margin-bottom:0}
.ope-air-route-scope{margin:2px 0 0;padding:12px 15px;border:1px solid var(--line);border-radius:8px;background:#f6fbfb}.ope-air-route-scope legend{padding:0 5px;font-size:13px;font-weight:750}.ope-air-route-scope label{display:flex;align-items:center;gap:8px;margin:7px 0;font-weight:500}.ope-air-route-scope input[type=radio]{accent-color:var(--turquoise-dark)}
.ope-bulk-save{position:sticky;top:76px;z-index:10;display:flex;align-items:center;gap:12px;flex-wrap:wrap;padding:10px 12px;border:1px solid var(--line);border-radius:9px;background:#fff;box-shadow:0 3px 10px rgb(6 31 32 / 8%)}.ope-bulk-save .note{margin:0}@media(max-width:760px){.ope-bulk-save{top:70px}}
</style></head><body>
<header class="topbar"><a class="brand" href="{{ route('operations.dashboard') }}"><span class="brand-mark">4N</span><span><strong>Operaciones</strong><small>4N Logística · Primera milla</small></span></a><div class="user-area"><a href="{{ route('portal.home') }}">Inicio</a> · <a href="{{ route('portal.profile') }}">{{ auth()->user()->name }}</a></div></header>
<div class="shell"><aside class="sidebar" aria-label="Menú Operaciones">
@foreach(['dashboard'=>['Procesos','grid'], 'loads.index'=>['Maestro Geolize','truck']] as $name=>$item)
<a class="nav-link {{ request()->routeIs('operations.'.$name) && ($name !== 'loads.index' || request()->route('type') === 'master') ? 'active' : '' }}" href="{{ route('operations.'.$name, $name === 'loads.index' ? ['type'=>'master'] : []) }}">@include('portal.icon',['icon'=>$item[1]]) {{ $item[0] }}</a>
@endforeach
<details @if(request()->route('type') === 'reception' || request()->routeIs('operations.system-receptions.*')) open @endif>
<summary class="nav-summary {{ request()->route('type') === 'reception' || request()->routeIs('operations.system-receptions.*') ? 'active' : '' }}">@include('portal.icon',['icon'=>'truck']) <span class="nav-text">Recepción de bultos</span></summary>
<div class="subnav">
<a class="{{ request()->routeIs('operations.system-receptions.*') ? 'active' : '' }}" href="{{ route('operations.system-receptions.index') }}">Recepción Sistema</a>
<a class="{{ request()->route('type') === 'reception' ? 'active' : '' }}" href="{{ route('operations.loads.index','reception') }}">Cargas Excel anteriores</a>
</div></details>
<details @if(request()->routeIs('operations.setup','operations.transport','operations.transport.update','operations.post-origins','operations.post-origins.update')) open @endif>
<summary class="nav-summary {{ request()->routeIs('operations.setup','operations.transport','operations.transport.update','operations.post-origins','operations.post-origins.update') ? 'active' : '' }}">@include('portal.icon',['icon'=>'settings']) <span class="nav-text">Agencias y guías</span></summary>
<div class="subnav">
<a class="{{ request()->routeIs('operations.setup') ? 'active' : '' }}" href="{{ route('operations.setup') }}">Relación de agencias</a>
<a class="{{ request()->routeIs('operations.transport') && request('type') !== 'posta' ? 'active' : '' }}" href="{{ route('operations.transport') }}#troncales">Troncales</a>
<a class="{{ request()->routeIs('operations.transport') && request('type') === 'posta' ? 'active' : '' }}" href="{{ route('operations.transport') }}#postas">Posta 1 y Posta 2</a>
<a class="{{ request()->routeIs('operations.post-origins') ? 'active' : '' }}" href="{{ route('operations.post-origins') }}">Orígenes de postas</a>
</div></details>
<a class="nav-link" href="{{ route('portal.home') }}">@include('portal.icon',['icon'=>'arrow-left']) Volver al inicio</a>
<p class="note" style="padding:12px">El peso de Operaciones prevalece; Geolize se usa si falta.</p>
</aside><main class="content">
@if(session('status'))<div class="success" role="status">{{ session('status') }}</div>@endif
@if($errors->any())<div class="error" role="alert">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
@yield('content')</main></div>@stack('scripts')</body></html>
