@extends('provider-payments::layout')
@section('title', 'Trabajar Registros de Courier')
@push('styles')
<style>
.compile-period{display:flex;align-items:end;gap:12px;margin-bottom:20px}.compile-period label{display:grid;gap:6px;font-weight:700}.compile-period select{padding:10px;min-width:180px;border:1px solid var(--line);border-radius:8px}.compile-processes{display:grid;gap:12px;margin:18px 0}.compile-process{display:flex;align-items:center;gap:12px;padding:15px;border:1px solid var(--line);border-radius:9px}.compile-process strong{min-width:110px}.compile-process small{color:var(--muted)}.compile-table{overflow:auto;max-height:65vh}.compile-table table{min-width:2300px}.compile-table th{position:sticky;top:0}.compile-status{padding:14px;margin:16px 0;background:#e8fbfa;border-left:4px solid var(--turquoise-dark)}.non-payable{margin:18px 0}.non-payable ul{margin:8px 0 16px;padding-left:20px}
.worked-filters{display:grid;grid-template-columns:repeat(4,minmax(170px,1fr));gap:12px;margin:18px 0}.worked-filters label{display:grid;gap:6px;font-size:12px;font-weight:800;text-transform:uppercase}.worked-filters select{width:100%;padding:10px;border:1px solid var(--line);border-radius:8px;background:#fff}.worked-filter-actions{display:flex;align-items:end;gap:8px}@media(max-width:950px){.worked-filters{grid-template-columns:repeat(2,minmax(170px,1fr))}}@media(max-width:600px){.worked-filters{grid-template-columns:1fr}}
.compile-toolbar{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:10px 0}.compile-toolbar>.button{margin-left:auto}.compile-toolbar>.button,.compile-toolbar>form>button{white-space:nowrap}.compile-period{margin:0}.compile-period label{font-size:12px;gap:3px}.compile-period select{padding:7px;min-width:125px}.compile-period button{padding:8px 12px}.compile-menu{position:relative}.compile-menu>summary{display:inline-flex;align-items:center;min-height:36px;list-style:none;cursor:pointer;padding:8px 12px;border:1px solid var(--line);border-radius:7px;background:#fff;color:var(--turquoise-dark);font-size:13px;font-weight:700}.compile-menu>summary::-webkit-details-marker{display:none}.compile-menu>summary::after{content:' ▾'}.compile-menu[open]>summary{background:#e8fbfa}.compile-menu .menu-panel{position:absolute;top:calc(100% + 5px);left:0;z-index:10;width:min(440px,calc(100vw - 40px));max-height:65vh;overflow:auto;padding:14px;box-shadow:0 12px 28px #071f2430}.compile-menu .menu-panel h2{font-size:17px;margin:0 0 10px}.compile-menu .menu-panel p{margin:6px 0 10px}.compile-processes{gap:6px;margin:10px 0}.compile-process{padding:8px;gap:8px;flex-wrap:wrap}.compile-process strong{min-width:75px}.compile-menu .non-payable{margin:0}.compile-menu .non-payable ul{margin:5px 0 10px}.worked-filters{grid-template-columns:repeat(5,minmax(130px,1fr));gap:7px 10px;margin:8px 0 12px;padding:12px}.worked-filters label{gap:3px;font-size:11px}.worked-filters select{padding:7px;font-size:13px}.worked-filter-actions button,.worked-filter-actions .button{padding:8px 10px}.compile-table{padding:10px}.compile-table+nav{margin-top:8px}@media(max-width:1100px){.worked-filters{grid-template-columns:repeat(3,minmax(150px,1fr))}}@media(max-width:650px){.compile-toolbar{align-items:stretch}.compile-toolbar>.button{margin-left:0}.compile-menu .menu-panel{position:static;width:100%;box-shadow:none}.worked-filters{grid-template-columns:repeat(2,minmax(130px,1fr))}}@media(max-width:420px){.worked-filters{grid-template-columns:1fr}}
.compile-table table{min-width:2750px;font-size:13px;line-height:1.35}
.compile-table th,.compile-table td{padding:7px 9px;vertical-align:top}
.compile-table th{font-size:11px;line-height:1.3}
.compile-table td{font-size:13px;overflow-wrap:break-word}
.compile-table td:nth-child(7),.compile-table td:nth-child(8),.compile-table td:nth-child(13),.compile-table td:nth-child(15),.compile-table td:nth-child(16),.compile-table td:nth-child(20){white-space:nowrap}
.compile-heading{display:flex;align-items:center;justify-content:space-between;gap:20px;flex-wrap:wrap}.compile-heading h1{margin-bottom:0}.compile-heading .compile-period{flex-shrink:0}.compile-heading+.intro{margin-top:6px}@media(max-width:650px){.compile-heading{align-items:flex-start}.compile-heading .compile-period{width:100%}}
.compile-delete-form{display:grid;gap:10px}.compile-delete-form label{display:grid;gap:5px;font-size:13px;font-weight:700}.compile-delete-form select,.compile-delete-form input{width:100%;padding:8px;border:1px solid var(--line);border-radius:7px;background:#fff}.compile-delete-form button{background:#a33030}
.worked-filters{grid-template-columns:repeat(6,minmax(120px,1fr))}
@media(max-width:1100px){.worked-filters{grid-template-columns:repeat(3,minmax(150px,1fr))}}
@media(max-width:650px){.worked-filters{grid-template-columns:repeat(2,minmax(130px,1fr))}}
@media(max-width:420px){.worked-filters{grid-template-columns:1fr}}
.compile-source-panel{margin:14px 0;padding:16px}.compile-source-panel h2{margin:0 0 6px;font-size:18px}.compile-source-panel p{margin:5px 0 12px}.compile-source-panel .compile-processes{display:grid;grid-template-columns:repeat(2,minmax(220px,1fr));gap:8px}.compile-source-panel .compile-process{margin:0}.compile-source-panel .compile-process .note{margin:0}.compile-source-panel .compile-process a{margin-left:auto}.compile-source-panel .compile-loading{margin-top:12px}@media(max-width:750px){.compile-source-panel .compile-processes{grid-template-columns:1fr}}
</style>
@endpush
@section('content')
<div class="page-heading"><a class="back" href="{{ route('provider-payments.courier-movements.compile') }}">← Compilar Movimientos</a><p class="eyebrow">Gestión operacional</p><h1>Trabajar Registros de Courier</h1><form class="compile-period" method="get"><label>Período AAAAMM<select name="period" onchange="this.form.submit()">@foreach($periods as $option)<option value="{{ $option }}" @selected($option === $period)>{{ $option }}</option>@endforeach</select></label><button type="submit">Ver</button></form></div>
<p class="intro">Consulta y prepara los movimientos del período seleccionado.</p>
@if(session('status'))<div class="compile-status">{{ session('status') }}</div>@endif
@if($errors->any())<div class="warning">{{ $errors->first() }}</div>@endif
@php($sourceProcessCount = (int) $processes->sum('total'))
@php($preparedSourceCount = (int) $processes->sum(fn ($process) => (int) ($paymentProcessCounts[$process->nombre_proceso] ?? 0)))
@if($sourceProcessCount > 0)
<section class="card compile-source-panel" aria-label="Preparar procesos Courier cargados">
    <h2>Procesos cargados del período {{ $period }}</h2>
    <p><strong>{{ number_format($sourceProcessCount, 0, ',', '.') }} movimientos cargados</strong> · <strong>{{ number_format($preparedSourceCount, 0, ',', '.') }} pagos preparados</strong></p>
    @if($preparedSourceCount < $sourceProcessCount)
    <p class="note">Prepara los procesos pendientes y luego usa «Asignar Pagos» para calcular sus montos. El resumen de abajo solo cuenta pagos preparados.</p>
    @else
    <p class="note">Estos procesos ya tienen registros de pago. Usa «Asignar Pagos» para calcular o actualizar los montos; los casos que no se puedan resolver quedarán «Sin definir» para revisión.</p>
    @endif
    <form method="post" action="{{ route('provider-payments.courier-movements.compile.store') }}" onsubmit="if (!this.querySelector('input[name=&quot;processes[]&quot;]:checked')) { alert('Selecciona al menos un proceso.'); return false; } this.querySelector('button[type=submit]').disabled=true; this.querySelector('.compile-loading').hidden=false;">@csrf<input type="hidden" name="period" value="{{ $period }}">
        <div class="compile-processes">@foreach($processes as $process)@php($processName = substr($process->nombre_proceso, 7))@php($workedCount = (int) ($paymentProcessCounts[$process->nombre_proceso] ?? 0))
            <div class="compile-process"><label><input type="checkbox" name="processes[]" value="{{ $processName }}" @checked($workedCount === 0)> <strong>{{ $processName === 'Variable' ? 'Variables' : $processName }}</strong></label><span>{{ number_format($process->total, 0, ',', '.') }} movimientos</span><small>{{ number_format($workedCount, 0, ',', '.') }} pagos preparados</small><a href="{{ route('provider-payments.movements.index', ['period' => $period, 'process' => $processName]) }}">Ver registros</a></div>
        @endforeach</div>
        <button type="submit">{{ $preparedSourceCount < $sourceProcessCount ? 'Preparar procesos seleccionados' : 'Actualizar procesos seleccionados' }}</button><div class="compile-loading" hidden><div class="progress-track"><div class="progress-bar"></div></div><p>Actualizando los registros de pago del período…</p></div>
    </form>
</section>
@endif
<div class="compile-toolbar" aria-label="Opciones de trabajo Courier">
<details class="compile-menu"><summary>Estados NO PAGAR ({{ number_format($nonPayableCounts->sum('total'), 0, ',', '.') }})</summary><section class="card menu-panel non-payable"><h2>Estados que no se deben pagar</h2><p>Período {{ $period }}: <strong>{{ number_format($nonPayableCounts->sum('total'), 0, ',', '.') }}</strong> registros sin condición NO y con estados NO PAGAR.</p>@if($nonPayableCounts->isNotEmpty())<ul>@foreach($nonPayableCounts as $statusCount)<li>{{ $statusCount->estado_envio }}: {{ number_format($statusCount->total, 0, ',', '.') }}</li>@endforeach</ul><form method="post" action="{{ route('provider-payments.courier-movements.compile.non-payable.mark') }}">@csrf<input type="hidden" name="period" value="{{ $period }}"><button type="submit">Marcar condición de pago NO</button></form>@else<p class="note">No hay registros pendientes de marcar NO en este período.</p>@endif</section></details>
<details class="compile-menu"><summary>Proveedores RM y Temuco ({{ number_format($fourNorthCandidates, 0, ',', '.') }})</summary><section class="card menu-panel non-payable"><h2>Proveedores RM y Temuco</h2><p>Período {{ $period }}: <strong>{{ number_format($fourNorthCandidates, 0, ',', '.') }}</strong> registros con asignación válida pendientes de actualizar.</p><p class="note">Conservados sin cambio: {{ number_format($fourNorthSummary['not_applicable'], 0, ',', '.') }} con N/A; {{ number_format($fourNorthSummary['without_user'], 0, ',', '.') }} sin repartidor; {{ number_format($fourNorthSummary['without_match'], 0, ',', '.') }} sin cruce o proveedor registrado.</p>@if($fourNorthCandidates > 0)<form method="post" action="{{ route('provider-payments.courier-movements.compile.providers-4n.update') }}" onsubmit="if (!confirm('¿Actualizar los proveedores RM y Temuco del período {{ $period }} con las asignaciones disponibles?')) return false; this.querySelector('button').disabled=true; this.querySelector('.compile-loading').hidden=false;">@csrf<input type="hidden" name="period" value="{{ $period }}"><button type="submit" style="background:var(--turquoise-dark)">Actualizar Proveedores RM y Temuco</button><div class="compile-loading" hidden><div class="progress-track"><div class="progress-bar"></div></div><p>Actualizando proveedores…</p></div></form>@else<p class="note">No quedan registros con asignación válida para actualizar.</p>@endif</section></details>
<details class="compile-menu"><summary>NO PAGAR Sin Usuario/Interno ({{ number_format($internalProviderCount, 0, ',', '.') }})</summary><section class="card menu-panel non-payable"><h2>NO PAGAR Sin Usuario/Interno</h2><p>Período {{ $period }}: <strong>{{ number_format($internalProviderCount, 0, ',', '.') }}</strong> registros del proveedor «4 Nortes Logistica SPA» sin condición NO.</p>@if($internalProviderCount > 0)<form method="post" action="{{ route('provider-payments.courier-movements.compile.internal-provider.mark') }}">@csrf<input type="hidden" name="period" value="{{ $period }}"><button type="submit">NO PAGAR Sin Usuario/Interno</button></form>@else<p class="note">No hay registros pendientes de marcar NO en este período.</p>@endif</section></details>
<a class="button" href="{{ route('provider-payments.courier-movements.compile.keys.review', ['period' => $period]) }}" target="_blank" rel="noopener">Revisar Inconsistencias Llave CC ({{ number_format($missingKeyProviders, 0, ',', '.') }}) ↗</a>
<form method="post" action="{{ route('provider-payments.courier-movements.compile.payments.assign') }}" onsubmit="this.querySelector('button').disabled=true; this.querySelector('.compile-loading').hidden=false;">@csrf<input type="hidden" name="period" value="{{ $period }}"><button type="submit">Asignar Pagos</button><div class="compile-loading" hidden><div class="progress-track"><div class="progress-bar"></div></div><p>Asignando pagos y tarifas…</p></div></form>
<details class="compile-menu" @if($errors->has('password') || $errors->has('process_name')) open @endif><summary>Eliminar registros cargados</summary><form class="card menu-panel compile-delete-form" method="post" action="{{ route('provider-payments.movements.processes.destroy') }}" onsubmit="if (!confirm('¿Procesar la eliminación seleccionada? En Especiales se eliminarán los movimientos nuevos y se restaurarán los pagos anteriores. Esta acción no se puede deshacer.')) return false; const button = this.querySelector('button[type=submit]'); button.disabled = true; button.textContent = 'Eliminando…'; return true;">@csrf @method('DELETE')<input type="hidden" name="return_to" value="work"><h2>Eliminar registros cargados</h2><p class="note">En Especiales se eliminan los movimientos nuevos y se restauran los pagos previos. Los otros procesos eliminan sus movimientos de origen y pagos vinculados.</p><label>AAAAMM-Proceso<select name="process_name" required><option value="">Selecciona un proceso</option>@foreach($loadedProcessOptions as $option)<option value="{{ $option->nombre_proceso }}" @selected(old('process_name') === $option->nombre_proceso)>{{ $option->nombre_proceso }} · Pagos: {{ number_format($paymentProcessCounts[$option->nombre_proceso] ?? 0, 0, ',', '.') }} · Origen: {{ number_format($option->total, 0, ',', '.') }}</option>@endforeach</select></label><label>Clave maestra<input type="password" name="password" required autocomplete="off"></label><button type="submit" @disabled($loadedProcessOptions->isEmpty())>Eliminar registros cargados</button></form></details>
</div>
@include('provider-payments::payment-summary', ['period' => $period, 'paymentDashboard' => $paymentDashboard])
<form class="card worked-filters" method="get" aria-label="Filtrar registros trabajados"><input type="hidden" name="period" value="{{ $period }}">@foreach(['process' => 'Proceso cargado', 'service' => 'Tipo de servicio', 'zone' => 'Zona', 'matrix' => 'Comuna matriz', 'client' => 'Cliente', 'payment_condition' => 'Condición de pago', 'provider_legal_name' => 'Razón social proveedor', 'operational_name' => 'Nombre operacional', 'document_type' => 'Tipo documento', 'courier_name' => 'Nombre repartidor', 'company' => 'Empresa mandante'] as $filter => $label)<label>{{ $label }}<select name="{{ $filter }}"><option value="">{{ $filter === 'process' ? 'Todos los procesos' : 'Todos' }}</option>@foreach($filterOptions[$filter] as $option)<option value="{{ $option }}" @selected(($filters[$filter] ?? '') === $option)>{{ $filter === 'payment_condition' && $option === '__unset__' ? 'Sin definir' : ($filter === 'process' ? $processOptionLabels[$option] : $option) }}</option>@endforeach</select></label>@endforeach<div class="worked-filter-actions"><button type="submit">Filtrar</button><a class="button" href="{{ route('provider-payments.courier-movements.compile.work', ['period' => $period]) }}">Limpiar</a></div></form>
<h2>Registros trabajados ({{ number_format($rows->total(), 0, ',', '.') }})</h2>
<p class="note">La zona se obtiene de Coberturas; si no se identifica un proveedor único, sus datos quedan pendientes.</p>
<div class="card compile-table"><table><thead><tr><th>Zona</th><th>Comuna matriz</th><th>Tipo Pago</th><th>Tipo de servicio</th><th>Proceso</th><th>Período</th><th>Seguimiento paquete</th><th>Guía de despacho</th><th>Fecha</th><th>Dirección</th><th>Comuna destino</th><th>Comerciante (Pila)</th><th>RUT cliente</th><th>Razón social cliente</th><th>Peso Final</th><th>Valor</th><th>Estado envío</th><th>Condición de pago</th><th>Razón social proveedor</th><th>RUT proveedor</th><th>Nombre operacional</th><th>Tipo documento</th><th>Nombre repartidor</th><th>Usuario entrega</th><th>Empresa mandante</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ $row->zona }}</td><td>{{ $row->comuna_matriz }}</td><td>{{ $row->tipo_pago }}</td><td>{{ $row->courierMovement?->service_name ?: $row->service_name ?: '—' }}</td><td>{{ $row->nombre_proceso }}</td><td>{{ $row->periodo }}</td><td>{{ $row->seguimiento_paquete }}</td><td>{{ $row->courierMovement?->dispatch_guide ?: '—' }}</td><td>{{ $row->fecha?->format('d-m-Y') }}</td><td>{{ $row->direccion }}</td><td>{{ $row->comuna_destino }}</td><td>{{ $row->comerciante_pila }}</td><td>{{ $row->rut_cliente }}</td><td>{{ $row->razon_social_cliente }}</td><td>{{ $row->peso_final }}</td><td>{{ $row->valor === null ? '—' : '$ '.number_format($row->valor, 0, ',', '.') }}</td><td>{{ $row->estado_envio }}</td><td>{{ $row->condicion_pago ?: '—' }}</td><td>{{ $row->razon_social_proveedor }}</td><td>{{ $row->rut_proveedor }}</td><td>{{ $row->nombre_operacional }}</td><td>{{ $row->tipo_documento }}</td><td>{{ $row->nombre_repartidor }}</td><td>{{ $row->usuario_entrega }}</td><td>{{ $row->empresa_mandante }}</td></tr>@empty<tr><td colspan="25">Aún no hay registros trabajados para este período.</td></tr>@endforelse</tbody></table></div>
@include('provider-payments::partials.pagination', ['paginator' => $rows])
@endsection
