@extends('provider-payments::layout')
@section('title', 'Trabajar Registros de Courier')
@push('styles')
<style>
.compile-period{display:flex;align-items:end;gap:12px;margin-bottom:20px}.compile-period label{display:grid;gap:6px;font-weight:700}.compile-period select{padding:10px;min-width:180px;border:1px solid var(--line);border-radius:8px}.compile-processes{display:grid;gap:12px;margin:18px 0}.compile-process{display:flex;align-items:center;gap:12px;padding:15px;border:1px solid var(--line);border-radius:9px}.compile-process strong{min-width:110px}.compile-process small{color:var(--muted)}.compile-table{overflow:auto;max-height:65vh}.compile-table table{min-width:2300px}.compile-table th{position:sticky;top:0}.compile-status{padding:14px;margin:16px 0;background:#e8fbfa;border-left:4px solid var(--turquoise-dark)}.non-payable{margin:18px 0}.non-payable button{background:#a33030}.non-payable button:hover{background:#842525}.non-payable ul{margin:8px 0 16px;padding-left:20px}
.worked-filters{display:grid;grid-template-columns:repeat(4,minmax(170px,1fr));gap:12px;margin:18px 0}.worked-filters label{display:grid;gap:6px;font-size:12px;font-weight:800;text-transform:uppercase}.worked-filters select{width:100%;padding:10px;border:1px solid var(--line);border-radius:8px;background:#fff}.worked-filter-actions{display:flex;align-items:end;gap:8px}@media(max-width:950px){.worked-filters{grid-template-columns:repeat(2,minmax(170px,1fr))}}@media(max-width:600px){.worked-filters{grid-template-columns:1fr}}
.compile-toolbar{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:12px 0}.compile-period{margin:0}.compile-period label{font-size:12px;gap:3px}.compile-period select{padding:8px;min-width:125px}.compile-period button{padding:9px 12px}.compile-menu{position:relative}.compile-menu>summary{list-style:none;cursor:pointer;padding:10px 13px;border:1px solid var(--line);border-radius:8px;background:#fff;color:var(--turquoise-dark);font-weight:700}.compile-menu>summary::-webkit-details-marker{display:none}.compile-menu>summary::after{content:' ▾'}.compile-menu[open]>summary{background:#e8fbfa}.compile-menu .menu-panel{position:absolute;top:calc(100% + 5px);left:0;z-index:10;width:min(440px,calc(100vw - 40px));max-height:65vh;overflow:auto;padding:16px;box-shadow:0 12px 28px #071f2430}.compile-menu .menu-panel h2{font-size:18px;margin:0 0 10px}.compile-menu .menu-panel p{margin:6px 0 10px}.compile-processes{gap:6px;margin:10px 0}.compile-process{padding:8px;gap:8px;flex-wrap:wrap}.compile-process strong{min-width:75px}.compile-menu .non-payable{margin:0}.compile-menu .non-payable ul{margin:5px 0 10px}.worked-filters{grid-template-columns:repeat(5,minmax(130px,1fr));gap:7px 10px;margin:8px 0 12px;padding:14px}.worked-filters label{gap:3px;font-size:11px}.worked-filters select{padding:7px;font-size:13px}.worked-filter-actions button,.worked-filter-actions .button{padding:8px 10px}.compile-table{padding:10px}.compile-table+nav{margin-top:8px}@media(max-width:1100px){.worked-filters{grid-template-columns:repeat(3,minmax(150px,1fr))}}@media(max-width:650px){.compile-toolbar{align-items:stretch}.compile-menu .menu-panel{position:static;width:100%;box-shadow:none}.worked-filters{grid-template-columns:repeat(2,minmax(130px,1fr))}}@media(max-width:420px){.worked-filters{grid-template-columns:1fr}}
.compile-heading{display:flex;align-items:center;justify-content:space-between;gap:20px;flex-wrap:wrap}.compile-heading h1{margin-bottom:0}.compile-heading .compile-period{flex-shrink:0}.compile-heading+.intro{margin-top:6px}@media(max-width:650px){.compile-heading{align-items:flex-start}.compile-heading .compile-period{width:100%}}
.key-review-menu .menu-panel{left:auto;right:0;width:min(850px,calc(100vw - 40px))}.missing-key-provider{padding:12px 0;border-top:1px solid var(--line)}.missing-key-provider>p{margin:4px 0 10px}.missing-key-form{display:grid;grid-template-columns:repeat(3,minmax(120px,1fr));gap:8px}.missing-key-form label{display:grid;gap:4px;font-size:12px;font-weight:700}.missing-key-form select{width:100%;min-width:0;padding:8px;border:1px solid var(--line);border-radius:8px;background:#fff}.missing-key-actions{display:flex;align-items:center;gap:12px;grid-column:1/-1}.missing-key-actions a{font-size:13px}.key-review-generate{margin:8px 0 14px}@media(max-width:750px){.missing-key-form{grid-template-columns:repeat(2,minmax(120px,1fr))}}@media(max-width:440px){.missing-key-form{grid-template-columns:1fr}}
</style>
@endpush
@section('content')
<a class="back" href="{{ route('provider-payments.courier-movements.compile') }}">← Compilar Movimientos</a>
<p class="eyebrow">Gestión operacional</p><div class="compile-heading"><h1>Trabajar Registros de Courier</h1><form class="compile-period" method="get"><label>Período AAAAMM<select name="period" onchange="this.form.submit()">@foreach($periods as $option)<option value="{{ $option }}" @selected($option === $period)>{{ $option }}</option>@endforeach</select></label><button type="submit">Ver</button></form></div>
<p class="intro">Consulta y prepara los movimientos del período seleccionado.</p>
@if(session('status'))<div class="compile-status">{{ session('status') }}</div>@endif
@if($errors->any())<div class="warning">{{ $errors->first() }}</div>@endif
<div class="compile-toolbar" aria-label="Opciones de trabajo Courier">
<details class="compile-menu" @if($errors->any()) open @endif><summary>Procesos disponibles</summary><form class="card menu-panel" method="post" action="{{ route('provider-payments.courier-movements.compile.store') }}" onsubmit="this.querySelector('button[type=submit]').disabled=true;this.querySelector('.compile-loading').hidden=false;">@csrf<input type="hidden" name="period" value="{{ $period }}"><h2>Procesos disponibles</h2>
<div class="compile-processes">@forelse($processes as $process)<label class="compile-process"><input type="checkbox" name="processes[]" value="{{ substr($process->nombre_proceso, 7) }}"><strong>{{ substr($process->nombre_proceso, 7) }}</strong><span>{{ number_format($process->total, 0, ',', '.') }} movimientos</span><small>{{ number_format($compiled[$process->nombre_proceso] ?? 0, 0, ',', '.') }} trabajados</small></label>@empty<p>No hay procesos de Variables, Lanas o Retornos en este período.</p>@endforelse</div>
@if($processes->isNotEmpty())<button type="submit">Trabajar procesos seleccionados</button><div class="compile-loading" hidden><div class="progress-track"><div class="progress-bar"></div></div><p>Preparando registros…</p></div>@endif</form></details>
<details class="compile-menu"><summary>Estados NO PAGAR ({{ number_format($nonPayableCounts->sum('total'), 0, ',', '.') }})</summary><section class="card menu-panel non-payable"><h2>Estados que no se deben pagar</h2><p>Período {{ $period }}: <strong>{{ number_format($nonPayableCounts->sum('total'), 0, ',', '.') }}</strong> registros trabajados con estados marcados NO PAGAR.</p>@if($nonPayableCounts->isNotEmpty())<ul>@foreach($nonPayableCounts as $statusCount)<li>{{ $statusCount->estado_envio }}: {{ number_format($statusCount->total, 0, ',', '.') }}</li>@endforeach</ul><form method="post" action="{{ route('provider-payments.courier-movements.compile.non-payable.destroy') }}" onsubmit="return confirm('¿Eliminar los {{ number_format($nonPayableCounts->sum('total'), 0, ',', '.') }} registros NO PAGAR del período {{ $period }}? Los movimientos originales se conservarán.')">@csrf @method('DELETE')<input type="hidden" name="period" value="{{ $period }}"><button type="submit">Eliminar registros con estados NO PAGAR</button></form>@else<p class="note">No hay registros NO PAGAR para eliminar en este período.</p>@endif</section></details>
<details class="compile-menu"><summary>Proveedores RM y Temuco ({{ number_format($fourNorthCandidates, 0, ',', '.') }})</summary><section class="card menu-panel non-payable"><h2>Proveedores RM y Temuco</h2><p>Período {{ $period }}: <strong>{{ number_format($fourNorthCandidates, 0, ',', '.') }}</strong> registros del proveedor 4N con comuna matriz RM o Temuco pendientes de revisar.</p><p class="note">El cruce usa RUT del proveedor, comuna matriz y nombre del repartidor. Las asignaciones N/A conservan el proveedor 4N.</p>@if($fourNorthCandidates > 0)<form method="post" action="{{ route('provider-payments.courier-movements.compile.providers-4n.update') }}" onsubmit="if (!confirm('¿Actualizar los proveedores RM y Temuco del período {{ $period }} con las asignaciones disponibles?')) return false; this.querySelector('button').disabled=true; this.querySelector('.compile-loading').hidden=false;">@csrf<input type="hidden" name="period" value="{{ $period }}"><button type="submit" style="background:var(--turquoise-dark)">Actualizar Proveedores RM y Temuco</button><div class="compile-loading" hidden><div class="progress-track"><div class="progress-bar"></div></div><p>Actualizando proveedores…</p></div></form>@endif</section></details>
<details class="compile-menu"><summary>Limpiar Proveedor interno y Sin usuario ({{ number_format($internalProviderCount, 0, ',', '.') }})</summary><section class="card menu-panel non-payable"><h2>Limpiar Proveedor interno y Sin usuario</h2><p>Período {{ $period }}: <strong>{{ number_format($internalProviderCount, 0, ',', '.') }}</strong> registros trabajados con razón social del proveedor «4 Nortes Logistica SPA».</p>@if($internalProviderCount > 0)<form method="post" action="{{ route('provider-payments.courier-movements.compile.internal-provider.destroy') }}" onsubmit="return confirm('¿Eliminar los {{ number_format($internalProviderCount, 0, ',', '.') }} registros de 4 Nortes Logistica SPA del período {{ $period }}? Los movimientos originales se conservarán.')">@csrf @method('DELETE')<input type="hidden" name="period" value="{{ $period }}"><button type="submit">Limpiar Proveedor interno y Sin usuario</button></form>@else<p class="note">No hay registros de este proveedor para eliminar en el período.</p>@endif</section></details>
<details class="compile-menu key-review-menu" @if(request()->boolean('review_keys') || $errors->any()) open @endif>
    <summary>Revisar Inconsistencias Llave CC ({{ number_format($missingKeyProviders, 0, ',', '.') }})</summary>
    <section class="card menu-panel">
        <h2>Llaves CC por configurar</h2>
        <p class="note">Período {{ $period }}: {{ number_format($missingKeyProviders, 0, ',', '.') }} proveedores con combinaciones de cliente y servicio sin llave activa con centro de costo.</p>
        @if($missingKeyCombinations > 0)
            <form class="key-review-generate" method="post" action="{{ route('provider-payments.courier-movements.compile.keys.generate') }}" onsubmit="this.querySelector('button').disabled=true">
                @csrf<input type="hidden" name="period" value="{{ $period }}">
                <button type="submit">Generar {{ number_format($missingKeyCombinations, 0, ',', '.') }} {{ $missingKeyCombinations === 1 ? 'llave faltante' : 'llaves faltantes' }}</button>
                <p class="note">Se crean con centro de costo 0, condición NO y estado Inactiva.</p>
            </form>
        @endif
        @forelse($keyReviewGroups as $group)
            <div class="missing-key-provider">
                <strong>{{ $group->provider_name }}</strong> · {{ $group->provider_tax_id }}
                <p class="note">{{ $group->client_name }} · {{ $group->service_name }} · {{ number_format($group->movements, 0, ',', '.') }} registros trabajados</p>
                @if($group->key)
                    <form class="missing-key-form" method="post" action="{{ route('provider-payments.maintainers.llave-centro-costos.update', $group->key) }}">
                        @csrf @method('PUT')
                        <input type="hidden" name="return_period" value="{{ $period }}">
                        <input type="hidden" name="agent_name" value="{{ $group->key->agent_name }}">
                        <label>Centro de costo<select name="cost_center_code" required>@foreach($keyReviewCenters as $center)<option value="{{ $center->cost_center_code }}" @selected((string) $group->key->cost_center_code === (string) $center->cost_center_code)>{{ $center->cost_center_code }} · {{ $center->dispatch_guide_detail }}</option>@endforeach</select></label>
                        <label>Condición de pago<select name="payment_status"><option value="NO" @selected($group->key->payment_status === 'NO')>NO</option><option value="SI" @selected($group->key->payment_status === 'SI')>SI</option><option value="REVISAR" @selected($group->key->payment_status === 'REVISAR')>REVISAR</option></select></label>
                        <label>Estado<select name="is_active"><option value="0" @selected(! $group->key->is_active)>Inactiva</option><option value="1" @selected($group->key->is_active)>Activa</option></select></label>
                        <div class="missing-key-actions"><button type="submit">Guardar llave</button><a href="{{ route('provider-payments.maintainers.llave-centro-costos', ['provider' => $group->provider_tax_id]) }}" target="_blank" rel="noopener">Ver en Llave CC ↗</a></div>
                    </form>
                @else
                    <p class="note">Llave pendiente de generar. Quedará con centro 0, pago NO e Inactiva.</p>
                @endif
            </div>
        @empty
            <p>No hay combinaciones de proveedor, cliente y servicio pendientes de configurar en este período.</p>
        @endforelse
    </section>
</details>
</div>
<form class="card worked-filters" method="get" aria-label="Filtrar registros trabajados"><input type="hidden" name="period" value="{{ $period }}">@foreach(['zone' => 'Zona', 'matrix' => 'Comuna matriz', 'client' => 'Cliente', 'client_legal_name' => 'Razón social cliente', 'provider_legal_name' => 'Razón social proveedor', 'operational_name' => 'Nombre operacional', 'document_type' => 'Tipo documento', 'courier_name' => 'Nombre repartidor', 'company' => 'Empresa mandante'] as $filter => $label)<label>{{ $label }}<select name="{{ $filter }}"><option value="">Todos</option>@foreach($filterOptions[$filter] as $option)<option value="{{ $option }}" @selected(($filters[$filter] ?? '') === $option)>{{ $option }}</option>@endforeach</select></label>@endforeach<div class="worked-filter-actions"><button type="submit">Filtrar</button><a class="button" href="{{ route('provider-payments.courier-movements.compile.work', ['period' => $period]) }}">Limpiar</a></div></form>
<h2>Registros trabajados ({{ number_format($rows->total(), 0, ',', '.') }})</h2>
<p class="note">La zona se obtiene de Coberturas; si no se identifica un proveedor único, sus datos quedan pendientes.</p>
<div class="card compile-table"><table><thead><tr><th>Zona</th><th>Comuna matriz</th><th>Tipo Pago</th><th>Proceso</th><th>Período</th><th>Seguimiento paquete</th><th>Fecha</th><th>Dirección</th><th>Comuna destino</th><th>Comerciante (Pila)</th><th>RUT cliente</th><th>Razón social cliente</th><th>Peso Final</th><th>Valor</th><th>Estado envío</th><th>Razón social proveedor</th><th>RUT proveedor</th><th>Nombre operacional</th><th>Tipo documento</th><th>Nombre repartidor</th><th>Usuario entrega</th><th>Empresa mandante</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ $row->zona }}</td><td>{{ $row->comuna_matriz }}</td><td>{{ $row->tipo_pago }}</td><td>{{ $row->nombre_proceso }}</td><td>{{ $row->periodo }}</td><td>{{ $row->seguimiento_paquete }}</td><td>{{ $row->fecha?->format('d-m-Y') }}</td><td>{{ $row->direccion }}</td><td>{{ $row->comuna_destino }}</td><td>{{ $row->comerciante_pila }}</td><td>{{ $row->rut_cliente }}</td><td>{{ $row->razon_social_cliente }}</td><td>{{ $row->peso_final }}</td><td>{{ $row->valor === null ? '—' : '$ '.number_format($row->valor, 0, ',', '.') }}</td><td>{{ $row->estado_envio }}</td><td>{{ $row->razon_social_proveedor }}</td><td>{{ $row->rut_proveedor }}</td><td>{{ $row->nombre_operacional }}</td><td>{{ $row->tipo_documento }}</td><td>{{ $row->nombre_repartidor }}</td><td>{{ $row->usuario_entrega }}</td><td>{{ $row->empresa_mandante }}</td></tr>@empty<tr><td colspan="22">Aún no hay registros trabajados para este período.</td></tr>@endforelse</tbody></table></div>
{{ $rows->links() }}
@endsection
