@extends('provider-payments::layout')
@section('title', 'Resumen de carga')
@push('styles')<style>.total{font-size:34px;font-weight:850;color:var(--turquoise-dark)}.summary-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:24px}.summary-grid.process-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.box{overflow:hidden}.box h2{margin:0;padding:16px 18px;border-bottom:3px solid var(--turquoise);font-size:18px}.confirmation{margin:20px 0;padding:18px;border-radius:10px;background:var(--turquoise-soft)}@media(max-width:850px){.summary-grid,.summary-grid.process-grid{grid-template-columns:1fr}}</style>@endpush
@section('content')
@php($uploadRoute = match($processType) {'lanas' => 'provider-payments.courier-movements.lanas', 'retornos' => 'provider-payments.courier-movements.retornos', default => 'provider-payments.courier-movements.upload'})
<a class="back" href="{{ route($uploadRoute) }}">← Cargar otro archivo</a><p class="eyebrow">Carga de movimientos</p><h1>Resumen de carga</h1><p class="intro">Verifica el contenido detectado antes de revisar los parámetros.</p>
<section class="card"><p><b>Archivo:</b> {{ $validation['file_name'] }}</p><div class="total">{{ number_format($validation['records'],0,',','.') }} registros procesados</div><p class="note">{{ $validation['missing_tracking'] }} sin seguimiento · {{ $validation['invalid_date'] }} con fecha no identificable · {{ $validation['missing_weight'] }} sin peso.</p>
@if(($validation['discarded_unlocated_route_pickups'] ?? 0) > 0)<p class="note">{{ number_format($validation['discarded_unlocated_route_pickups'], 0, ',', '.') }} registros de «Retiro en ruta» sin dirección ni comuna destino se descartarán y no se cargarán.</p>@endif
@if($processType === 'consolidado')
<div class="summary-grid process-grid" aria-label="Separación automática de procesos">
@foreach(['Variable', 'Lanas', 'Retornos', 'Peumo'] as $process)<article class="box"><h2>Proceso {{ $process }}</h2><p class="total" style="padding:12px 18px">{{ number_format($validation['process_counts'][$process] ?? 0, 0, ',', '.') }}</p></article>@endforeach
</div>
<p class="note">Lanas se identifica por comerciante. Comercial Peumo Ltda con «Servicio Standar (V. Trabajadores)» se separa como Peumo. Entre los demás registros, «Nombre del destinatario» que comience con «Desde » identifica Retornos; el resto queda en Variables.</p>
@if(($validation['missing_peumo_guide'] ?? 0) > 0)<p class="warning">{{ number_format($validation['missing_peumo_guide'], 0, ',', '.') }} bultos de Peumo no tienen guía de despacho. Quedarán pendientes de pago hasta corregirla.</p>@endif
@endif
@if($processType === 'retornos' || ($processType === 'consolidado' && ($validation['process_counts']['Retornos'] ?? 0) > 0))
<article class="box" style="margin-top:20px"><h2>Revisión agrupada de direcciones y comunas transformadas</h2><p class="note" style="padding:0 18px">Dirección final = Dirección - Comuna de destino. Comuna final = Nombre del destinatario sin el prefijo “Desde ”.</p><div class="table-wrap"><table><thead><tr><th>Dirección final</th><th>Comuna final</th><th>Registros</th></tr></thead><tbody>@forelse($validation['destination_preview'] as $destination)<tr><td>{{ $destination['address'] ?: '(Sin dirección)' }}</td><td>{{ $destination['commune'] ?: '(Sin comuna)' }}</td><td>{{ number_format($destination['count'],0,',','.') }}</td></tr>@empty<tr><td colspan="3">No se detectaron destinos.</td></tr>@endforelse</tbody></table></div></article>
@endif
<div class="confirmation"><b>¿Aceptas cargar esta información?</b><p class="note">Antes de incorporarla, revisaremos clientes, servicios, coberturas de comunas y pesos.</p><a class="button" href="{{ route('provider-payments.courier-movements.review-parameters') }}" id="review-link">Aceptar y revisar parámetros</a><div id="review-loading" hidden><p>Comparando clientes, servicios, coberturas y pesos…</p><progress></progress></div></div>
<div class="summary-grid"><article class="box"><h2>Registros por cliente</h2><table><thead><tr><th>Cliente / comerciante</th><th>Registros</th></tr></thead><tbody>@foreach($validation['merchant_counts'] as $name => $total)<tr><td>{{ $name }}</td><td>{{ number_format($total,0,',','.') }}</td></tr>@endforeach</tbody></table></article><article class="box"><h2>Registros por estado</h2><table><thead><tr><th>Estado</th><th>Registros</th></tr></thead><tbody>@foreach($validation['status_counts'] as $name => $total)<tr><td>{{ $name }}</td><td>{{ number_format($total,0,',','.') }}</td></tr>@endforeach</tbody></table></article></div></section>
@endsection
@push('scripts')<script>document.getElementById('review-link')?.addEventListener('click',function(){document.getElementById('review-loading').hidden=false;this.style.pointerEvents='none';});window.addEventListener('pageshow',function(){document.getElementById('review-loading').hidden=true;document.getElementById('review-link').style.pointerEvents='';});</script>@endpush
