@extends('provider-payments::layout')
@section('title', $processTitle)
@push('styles')<style>.upload-wrap{max-width:1100px}.file{padding:34px;border:2px dashed var(--turquoise);border-radius:11px;text-align:center}.file input{margin-top:15px}.result{margin-top:22px;padding:18px;border-radius:8px;background:var(--turquoise-soft);color:#245c5e}.result.error{background:#fff0f1;color:#992d3a}.progress{display:none;margin-top:20px}.progress.visible{display:block}label{display:block;margin:22px 0 8px;font-weight:750}.loaded-heading{display:flex;align-items:end;justify-content:space-between;gap:16px;flex-wrap:wrap}.loaded-heading h2{margin:0}.loaded-heading label{display:grid;gap:5px;margin:0;font-size:13px}.loaded-heading select{padding:8px;border:1px solid var(--line);border-radius:7px;background:#fff}.loaded-processes{display:grid;gap:8px;margin:14px 0}.loaded-process{display:flex;align-items:center;gap:12px;flex-wrap:wrap;padding:10px 12px;border:1px solid var(--line);border-radius:8px}.loaded-process strong{min-width:105px}.loaded-process .count{font-weight:800;font-variant-numeric:tabular-nums}.loaded-process .note{margin:0}.loaded-process a{margin-left:auto}.loaded-actions{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:650px){.loaded-process a{margin-left:0}}</style>@endpush
@section('content')
<div class="upload-wrap"><a class="back" href="{{ route('provider-payments.dashboard') }}">← Pago a Proveedores</a><p class="eyebrow">Carga Movimientos Courier</p><h1>{{ $processTitle }}</h1><p class="intro">@if($processType === 'consolidado')Carga una sola base Geolize. Se separará en Variables, Lanas, Retornos y Peumo, sin repetir seguimientos.@else Selecciona la base Geolize que se incorporará al proceso de pago.@endif</p>
@if ($processType === 'consolidado' && ($lastImport = session('courier_import_last_result')))
<div class="card" role="status"><h2>Última carga completada</h2><p><strong>{{ $lastImport['file_name'] }}</strong> · {{ $lastImport['process_name'] }}</p><p>{{ number_format($lastImport['loaded'], 0, ',', '.') }} movimientos incorporados; {{ number_format($lastImport['closed'], 0, ',', '.') }} seguimientos ya pagados y {{ number_format($lastImport['closed_period'], 0, ',', '.') }} duplicados de períodos cerrados quedaron sin cargar. {{ number_format($lastImport['excluded'], 0, ',', '.') }} registros se excluyeron de la importación.</p><p class="note">Peso Real sincronizado en {{ number_format($lastImport['weight_updated'], 0, ',', '.') }} movimientos abiertos.</p>@if ($lastImport['report_token'])<a class="button" href="{{ route('provider-payments.courier-movements.paid-report.download', $lastImport['report_token']) }}">Descargar Excel de seguimientos ya pagados</a>@endif</div>
@endif
@if ($processType === 'consolidado')
<section id="processes-loaded" class="card" aria-label="Procesos Courier cargados">
    <div class="loaded-heading"><h2>Procesos cargados</h2>@if($periods->isNotEmpty())<form method="get"><label>Período<select name="period" onchange="this.form.submit()">@foreach($periods as $option)<option value="{{ $option }}" @selected($option === $period)>{{ $option }}</option>@endforeach</select></label><noscript><button type="submit">Ver</button></noscript></form>@endif</div>
    @if($period !== '')
        <p class="note">Los movimientos de {{ $period }} están guardados. Para que aparezcan como pagos, debes trabajar los procesos.</p>
        <div class="loaded-processes">@foreach($processes as $process => $label)@php($sourceCount = (int) ($sourceCounts[$period.'-'.$process] ?? 0))@php($workedCount = (int) ($paymentCounts[$process] ?? 0) + (int) ($paymentCounts[$period.'-'.$process] ?? 0))
            <div class="loaded-process"><strong>{{ $label }}</strong><span class="count">{{ number_format($sourceCount, 0, ',', '.') }} {{ $sourceCount === 1 ? 'movimiento' : 'movimientos' }}</span><span class="note">{{ number_format($workedCount, 0, ',', '.') }} {{ $workedCount === 1 ? 'pago preparado' : 'pagos preparados' }}</span>@if($sourceCount > 0)<a href="{{ route('provider-payments.movements.index', ['period' => $period, 'process' => $process]) }}">Ver registros</a>@endif</div>
        @endforeach</div>
        @if($sourceCounts->sum() > 0)<div class="loaded-actions"><a class="button" href="{{ route('provider-payments.movements.index', ['period' => $period]) }}">Ver toda la planilla</a><a class="button" href="{{ route('provider-payments.courier-movements.compile.work', ['period' => $period]) }}">Trabajar procesos cargados</a></div>@endif
    @else<p class="note">Aún no hay procesos Courier cargados.</p>@endif
</section>
@endif
<div class="card"><form id="validation-form" action="{{ route('provider-payments.courier-movements.validate') }}" method="post" enctype="multipart/form-data">@csrf<input type="hidden" name="process_type" value="{{ $processType }}"><label for="file">Archivo de movimientos</label><div class="file"><div>Busca un archivo Excel o CSV</div><input id="file" name="file" type="file" accept=".xlsx,.csv" required></div><p class="note"><strong>Formato recomendado:</strong> CSV UTF-8 con extensión <b>.csv</b>. Alternativa: Excel <b>.xlsx</b>. Tamaño máximo: 100 MB.</p><p class="note">Validaremos seguimiento, fecha, peso y los datos necesarios antes de incorporarlos.@if($processType === 'consolidado') La base debe contener «Nombre del destinatario» para identificar Retornos.@endif Al completar la carga, Peso Real y Peso Final se sincronizan automáticamente en procesos abiertos.</p><button id="validate-button" type="submit">Validar archivo</button></form>
<div id="progress" class="progress" role="status"><div class="progress-track"><div class="progress-bar"></div></div><p>Subiendo y validando el archivo. Esto puede tomar unos momentos.</p></div>
@if ($errors->any())<div class="result error" role="alert">{{ $errors->first() }}</div>@endif
@if (isset($validation) || session('validation')) @php($validation = $validation ?? session('validation')) <div class="result"><strong>Resultado de la validación</strong><div><b>Archivo:</b> {{ $validation['file_name'] }}</div><div><b>Registros detectados:</b> {{ number_format($validation['records'], 0, ',', '.') }}</div></div>@endif
</div></div>
@endsection
@push('scripts')<script>const form=document.getElementById('validation-form'),file=document.getElementById('file'),progress=document.getElementById('progress'),button=document.getElementById('validate-button');form.addEventListener('submit',function(event){if(!file.files.length){event.preventDefault();file.setCustomValidity('Archivo con problema: selecciona un archivo. Formato recomendado: CSV UTF-8 con extensión .csv. También puedes usar Excel .xlsx.');file.reportValidity();return;}file.setCustomValidity('');if(form.checkValidity()){progress.classList.add('visible');button.disabled=true;button.textContent='Validando archivo...';}});file.addEventListener('change',function(){file.setCustomValidity('');});</script>@endpush
