@extends('provider-payments::layout')
@section('title', 'Resumen de carga')
@push('styles')<style>.total{font-size:34px;font-weight:850;color:var(--turquoise-dark)}.summary-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:24px}.box{overflow:hidden}.box h2{margin:0;padding:16px 18px;border-bottom:3px solid var(--turquoise);font-size:18px}.confirmation{margin:20px 0;padding:18px;border-radius:10px;background:var(--turquoise-soft)}@media(max-width:850px){.summary-grid{grid-template-columns:1fr}}</style>@endpush
@section('content')
<a class="back" href="{{ route($processType === 'lanas' ? 'provider-payments.courier-movements.lanas' : 'provider-payments.courier-movements.upload') }}">← Cargar otro archivo</a><p class="eyebrow">Carga de movimientos</p><h1>Resumen de carga</h1><p class="intro">Verifica el contenido detectado antes de revisar los parámetros.</p>
<section class="card"><p><b>Archivo:</b> {{ $validation['file_name'] }}</p><div class="total">{{ number_format($validation['records'],0,',','.') }} registros procesados</div><p class="note">{{ $validation['missing_tracking'] }} sin seguimiento · {{ $validation['invalid_date'] }} con fecha no identificable · {{ $validation['missing_weight'] }} sin peso.</p>
<div class="confirmation"><b>¿Aceptas cargar esta información?</b><p class="note">Antes de incorporarla, revisaremos clientes, servicios, coberturas de comunas y pesos.</p><a class="button" href="{{ route('provider-payments.courier-movements.review-parameters') }}" id="review-link">Aceptar y revisar parámetros</a><div id="review-loading" hidden><p>Comparando clientes, servicios, coberturas y pesos…</p><progress></progress></div></div>
<div class="summary-grid"><article class="box"><h2>Registros por cliente</h2><table><thead><tr><th>Cliente / comerciante</th><th>Registros</th></tr></thead><tbody>@foreach($validation['merchant_counts'] as $name => $total)<tr><td>{{ $name }}</td><td>{{ number_format($total,0,',','.') }}</td></tr>@endforeach</tbody></table></article><article class="box"><h2>Registros por estado</h2><table><thead><tr><th>Estado</th><th>Registros</th></tr></thead><tbody>@foreach($validation['status_counts'] as $name => $total)<tr><td>{{ $name }}</td><td>{{ number_format($total,0,',','.') }}</td></tr>@endforeach</tbody></table></article></div></section>
@endsection
@push('scripts')<script>document.getElementById('review-link')?.addEventListener('click',function(){document.getElementById('review-loading').hidden=false;this.style.pointerEvents='none';});window.addEventListener('pageshow',function(){document.getElementById('review-loading').hidden=true;document.getElementById('review-link').style.pointerEvents='';});</script>@endpush
