@extends('provider-payments::layout')
@section('title', 'Crear cobertura')
@push('styles')@include('provider-payments::partials.master-styles')<style>.help{padding:16px;border-radius:9px;background:var(--turquoise-soft)}.coverage-list{max-height:75vh;overflow:auto}</style>@endpush
@section('content')
<a class="back" href="{{ session()->has('courier_review') ? route('provider-payments.courier-movements.review-parameters') : route('provider-payments.dashboard') }}">← Volver</a><p class="eyebrow">Mantenedor de coberturas</p><h1>Coberturas</h1><p class="intro">Crea una cobertura desde una plantilla o actualiza datos operativos. La comuna y el proveedor quedan protegidos porque participan en los cruces.</p>
@if(session('status'))<div class="status">{{ session('status') }}</div>@endif
<div class="master-grid"><div class="card"><h2>Crear cobertura</h2><form class="form-grid" method="post" action="{{ route('provider-payments.maintainers.coberturas.store') }}">@csrf
<label class="wide">Nueva comuna<input name="commune_name" value="{{ old('commune_name', $commune) }}" required maxlength="150"></label>
<label class="wide">Cobertura que se usará como plantilla<select name="template_id" required><option value="">Selecciona una cobertura existente</option>@foreach($templates as $template)<option value="{{ $template->id }}" @selected((string) old('template_id') === (string) $template->id)>{{ $template->commune_name }} · {{ $template->provider_name_source ?: $template->provider_tax_id }} · {{ $template->zone }} · {{ $template->route_code }}</option>@endforeach</select></label>
<p class="help">Se copiarán proveedor, comuna matriz, zona, retorno, frecuencia, tipo de entrega, región, ruta, troncal, posta y demás parámetros de la plantilla.</p>
@if($errors->any())<p class="warning wide">{{ $errors->first() }}</p>@endif<button class="wide" type="submit">Crear nueva cobertura</button></form></div>
<section class="coverage-list"><h2>Coberturas creadas <span class="note">({{ $coverages->count() }})</span></h2>@foreach($coverages as $coverage)<details class="record"><summary>{{ $coverage->commune_name }} · {{ $coverage->provider_name_source ?: $coverage->provider_tax_id }} <span class="badge {{ $coverage->is_active ? '' : 'off' }}">{{ $coverage->is_active ? 'Activa' : 'Inactiva' }}</span></summary><form class="form-grid" method="post" action="{{ route('provider-payments.maintainers.coberturas.update', $coverage) }}">@csrf @method('PUT')<div class="protected wide"><strong>Llaves protegidas:</strong> {{ $coverage->commune_name }} · {{ $coverage->provider_tax_id ?: 'sin RUT proveedor' }}</div><label>Comuna matriz<input name="matrix_commune_name" value="{{ $coverage->matrix_commune_name }}"></label><label>Zona<input name="zone" value="{{ $coverage->zone }}" required></label><label>Pago retorno<select name="return_payment_applies"><option value="1" @selected($coverage->return_payment_applies)>Sí</option><option value="0" @selected(!$coverage->return_payment_applies)>No</option></select></label><label>Valor retorno<input type="number" name="return_value" value="{{ $coverage->return_value }}" min="0"></label><label>Frecuencia<input name="delivery_frequency" value="{{ $coverage->delivery_frequency }}"></label><label>Tipo entrega<input name="delivery_type" value="{{ $coverage->delivery_type }}"></label><label>Región<input type="number" name="region_code" value="{{ $coverage->region_code }}"></label><label>Ruta<input name="route_code" value="{{ $coverage->route_code }}"></label><label>Troncal<input name="trunk_name" value="{{ $coverage->trunk_name }}"></label><label>Posta<input name="post_name" value="{{ $coverage->post_name }}"></label><label>Vigente desde<input type="date" name="effective_from" value="{{ $coverage->effective_from?->format('Y-m-d') }}"></label><label>Vigente hasta<input type="date" name="effective_to" value="{{ $coverage->effective_to?->format('Y-m-d') }}"></label><label>Estado<select name="is_active"><option value="1" @selected($coverage->is_active)>Activa</option><option value="0" @selected(!$coverage->is_active)>Inactiva</option></select></label><button class="wide">Guardar cambios seguros</button></form></details>@endforeach</section></div>
@endsection
