@extends('provider-payments::layout')
@section('title', 'Resumen')
@push('styles')<style>.filter{display:flex;align-items:end;gap:12px;margin:18px 0;padding:14px 16px}.filter label{display:grid;gap:5px;font-size:13px;font-weight:750}.filter select{min-width:210px;padding:8px;border:1px solid var(--line);border-radius:7px;background:#fff}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:18px 0}.metric{padding:16px}.metric strong{display:block;margin-top:7px;color:#071b1d;font-size:26px}.metric.featured{background:var(--navy);color:#d2eeee}.service-counts{display:grid;gap:7px;margin-top:9px}.service-count{display:flex;justify-content:space-between;gap:12px;color:#fff;font-size:16px;font-weight:800}.service-count b{font-variant-numeric:tabular-nums}.process-manager{margin:0 0 20px;padding:16px}.process-manager h2{margin:0 0 6px}.process-delete-list{display:grid;gap:9px;margin-top:14px}.process-delete-row{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:10px;border:1px solid var(--line);border-radius:8px}.process-delete-row label{display:grid;gap:4px;font-size:12px;font-weight:700}.process-delete-row input{padding:8px;border:1px solid var(--line);border-radius:7px}.process-delete-row button{background:#b42318}.summary-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.box{overflow:hidden}.box h2{margin:0;padding:14px 16px;border-bottom:1px solid var(--line);font-size:16px}.empty{padding:18px;color:var(--muted)}@media(max-width:1050px){.metrics{grid-template-columns:1fr 1fr}}@media(max-width:900px){.filter{align-items:stretch;flex-direction:column}.metrics,.summary-grid{grid-template-columns:1fr}.process-delete-row{align-items:stretch;flex-direction:column}}</style>@endpush
@section('content')
<p class="eyebrow">Gestión operacional</p><h1>Resumen de pago a proveedores</h1><p class="intro">Estado general de los movimientos Courier y preparación de pagos.</p>
@if(session('status'))<div class="status">{{ session('status') }}</div>@endif
@if($errors->any())<div class="warning">{{ $errors->first() }}</div>@endif
<form class="card filter" method="get"><label>Año y mes del proceso<select name="period" onchange="this.form.submit()">@forelse($periods as $period)<option value="{{ $period }}" @selected($period === $selectedPeriod)>{{ substr($period,0,4) }}-{{ substr($period,4,2) }}</option>@empty<option value="">Sin procesos cargados</option>@endforelse</select></label><noscript><button type="submit">Filtrar</button></noscript><span class="note">Al ingresar se muestra automáticamente el año y mes más alto.</span></form>
@if($selectedPeriod !== '')
@include('provider-payments::payment-overview', ['period' => $selectedPeriod, 'paymentDashboard' => $paymentDashboard])
@endif
<section class="metrics"><a class="card metric" href="{{ route('provider-payments.movements.index', ['period' => $selectedPeriod]) }}" style="text-decoration:none"><span class="note">Registros cargados · Ver planilla</span><strong>{{ number_format($recordCount,0,',','.') }}</strong></a><article class="card metric"><span class="note">Clientes con movimientos</span><strong>{{ count($merchantCounts) }}</strong></article><article class="card metric"><span class="note">Estados registrados</span><strong>{{ count($statusCounts) }}</strong></article><article class="card metric featured"><span>Registros por servicio</span><div class="service-counts">@forelse($serviceCounts as $service)<a class="service-count" href="{{ route('provider-payments.movements.index', ['period' => $selectedPeriod, 'process' => $service->service_name]) }}" style="text-decoration:none"><span>{{ $service->service_name ?: 'Sin servicio' }}</span><b>{{ number_format($service->total,0,',','.') }}</b></a>@empty<div class="service-count"><span>Sin procesos cargados</span></div>@endforelse</div></article></section>
<section class="card process-manager"><h2>Eliminar procesos cargados</h2><p class="note">Elimina los movimientos del proceso seleccionado y todos sus registros de pago asociados. Requiere clave maestra.</p><div class="process-delete-list">@forelse($serviceCounts as $service)@php($fullProcessName = $selectedPeriod.'-'.$service->service_name)<form class="process-delete-row" method="post" action="{{ route('provider-payments.movements.processes.destroy') }}" onsubmit="if (!confirm('¿Eliminar {{ $fullProcessName }} con sus {{ number_format($service->total,0,',','.') }} movimientos y todos sus registros de pago asociados? Esta acción no se puede deshacer.')) return false; const button = this.querySelector('button[type=submit]'); button.disabled = true; button.textContent = 'Eliminando…'; return true;">@csrf @method('DELETE')<input type="hidden" name="process_name" value="{{ $fullProcessName }}"><span><strong>{{ $fullProcessName }}</strong> · {{ number_format($service->total,0,',','.') }} registros</span><label>Clave maestra <input type="password" name="password" required autocomplete="off"></label><button type="submit">Eliminar proceso</button></form>@empty<p class="empty">No hay procesos para eliminar en este período.</p>@endforelse</div></section>
<section class="summary-grid"><article class="box"><h2>Registros por cliente</h2>@forelse($merchantCounts as $row)@if($loop->first)<table><thead><tr><th>Comerciante</th><th>Registros</th></tr></thead><tbody>@endif<tr><td>{{ $row->merchant_name ?: 'Sin comerciante' }}</td><td>{{ number_format($row->total,0,',','.') }}</td></tr>@if($loop->last)</tbody></table>@endif @empty<p class="empty">Aún no hay movimientos Courier cargados.</p>@endforelse</article>
<article class="box"><h2>Registros por estado</h2>@forelse($statusCounts as $row)@if($loop->first)<table><thead><tr><th>Estado</th><th>Registros</th></tr></thead><tbody>@endif<tr><td>{{ $row->status ?: 'Sin estado' }}</td><td>{{ number_format($row->total,0,',','.') }}</td></tr>@if($loop->last)</tbody></table>@endif @empty<p class="empty">Aún no hay movimientos Courier cargados.</p>@endforelse</article></section>
@endsection
