@extends('provider-payments::layout')
@section('title', 'Peso Transformado')
@push('styles')
<style>
.weight-tabs{display:flex;gap:10px;margin:0 0 22px}.weight-tabs a{padding:10px 15px;border:1px solid var(--line);border-radius:8px;background:#fff;text-decoration:none;font-weight:750}.weight-tabs a.active{background:var(--turquoise-dark);color:#fff}.metric{font-size:28px;font-weight:850;color:var(--turquoise-dark)}.summary{display:grid;grid-template-columns:repeat(2,minmax(180px,260px));gap:14px;margin-bottom:20px}.summary .card{padding:18px}.status{margin-bottom:18px;padding:14px;border-left:4px solid var(--turquoise-dark);background:#e8fbfa}.badge{display:inline-block;padding:4px 9px;border-radius:99px;background:#e1f7ed;color:#16724a;font-size:12px;font-weight:750}.badge.off{background:#f5e5e3;color:#9b2c21}.weight-actions{display:flex;justify-content:space-between;align-items:center;gap:12px;margin:20px 0}.weight-editor{display:grid;grid-template-columns:minmax(120px,1fr) minmax(120px,1fr) auto;gap:10px;align-items:end}.weight-editor label{display:grid;gap:5px;font-size:12px;font-weight:800;text-transform:uppercase}.weight-editor input,.weight-editor select{width:100%;padding:9px;border:1px solid var(--line);border-radius:7px;background:#fff}.discovered{margin:0 0 24px}.discovered h2{margin-top:0}.discover-form{display:grid;grid-template-columns:minmax(120px,1fr) 140px auto;gap:10px;align-items:end}.discover-form label{display:grid;gap:5px;font-weight:750}.discover-form input{width:100%;padding:9px;border:1px solid var(--line);border-radius:7px}@media(max-width:800px){.weight-editor,.discover-form{grid-template-columns:1fr}.weight-actions{align-items:stretch;flex-direction:column}}
</style>
@endpush
@section('content')
<a class="back" href="{{ route('provider-payments.dashboard') }}">← Pago a Proveedores</a><p class="eyebrow">Mantenedor de pesos</p><h1>Peso Transformado</h1><p class="intro">Administra la equivalencia entre cada Peso Fuente recibido y el Peso Transformado utilizado por el proceso.</p>
<nav class="weight-tabs"><a class="active" href="{{ route('provider-payments.maintainers.pesos.transformados') }}">Peso Transformado</a><a href="{{ route('provider-payments.maintainers.pesos.reales') }}">Peso Real</a></nav>
@if(session('status'))<div class="status">{{ session('status') }}</div>@endif
<div class="summary"><div class="card"><span class="note">Pesos fuente registrados</span><div class="metric">{{ number_format($weights->count(), 0, ',', '.') }}</div></div><div class="card"><span class="note">Equivalencias activas</span><div class="metric">{{ number_format($weights->where('is_active', true)->count(), 0, ',', '.') }}</div></div></div>
<div class="weight-actions"><h2>Equivalencias registradas</h2><a class="button" href="{{ route('provider-payments.maintainers.pesos.transformados', ['discover' => 1]) }}">Buscar nuevos pesos</a></div>
@if($discovering)<section class="card discovered"><h2>Nuevos pesos encontrados <span class="note">({{ number_format($newWeights->count(), 0, ',', '.') }})</span></h2><p class="note">Valores agrupados desde movimientos_courier que todavía no existen en Peso Transformado.</p><div class="table-wrap"><table><thead><tr><th>Peso Fuente</th><th>Apariciones</th><th>Agregar equivalencia</th></tr></thead><tbody>@forelse($newWeights as $newWeight)<tr data-master-record><td>{{ $newWeight['source_weight'] }}</td><td>{{ number_format($newWeight['movement_count'], 0, ',', '.') }}</td><td><form class="discover-form" method="post" action="{{ route('provider-payments.maintainers.pesos.transformados.store') }}">@csrf<input type="hidden" name="return_to" value="discovery"><input type="hidden" name="source_weight" value="{{ $newWeight['source_weight'] }}"><span>{{ $newWeight['source_weight'] }}</span><label>Peso Transformado<input type="number" name="transformed_weight" min="1" step="1" value="{{ $newWeight['suggested_weight'] }}" required></label><button type="submit">Agregar</button></form></td></tr>@empty<tr><td colspan="3">No se encontraron pesos nuevos. Todos los pesos de movimientos_courier ya están creados.</td></tr>@endforelse</tbody></table></div></section>@endif
<section class="card"><div class="table-wrap"><table><thead><tr><th>Peso Fuente</th><th>Peso Transformado</th><th>Estado</th><th>Modificar</th></tr></thead><tbody>@forelse($weights as $weight)<tr data-master-record data-state="{{ $weight->is_active ? 'active' : 'inactive' }}"><td>{{ $weight->source_weight }}</td><td>{{ $weight->transformed_weight }}</td><td><span class="badge {{ $weight->is_active ? '' : 'off' }}">{{ $weight->is_active ? 'Activo' : 'Inactivo' }}</span></td><td><form class="weight-editor" method="post" action="{{ route('provider-payments.maintainers.pesos.transformados.update', $weight) }}" onsubmit="return confirm('¿Confirmas modificar la equivalencia del peso {{ $weight->source_weight }}?')">@csrf @method('PUT')<label>Peso Transformado<input type="number" name="transformed_weight" min="1" step="1" value="{{ $weight->transformed_weight }}" required></label><label>Estado<select name="is_active"><option value="1" @selected($weight->is_active)>Activo</option><option value="0" @selected(!$weight->is_active)>Inactivo</option></select></label><button type="submit">Modificar</button></form></td></tr>@empty<tr><td colspan="4">No hay pesos registrados.</td></tr>@endforelse</tbody></table></div></section>
@if($errors->any())<p class="warning">{{ $errors->first() }}</p>@endif
@endsection
