@extends('provider-payments::layout')
@section('title', 'Pesos Reales')
@push('styles')
<style>
.real-toolbar{display:flex;align-items:center;justify-content:space-between;gap:16px;margin:20px 0}.status{padding:14px;border-left:4px solid var(--turquoise-dark);background:#e8fbfa}.real-filters{display:grid;grid-template-columns:repeat(3,minmax(180px,1fr));gap:12px;margin:20px 0}.real-filters label{display:grid;gap:6px;font-size:12px;font-weight:800;text-transform:uppercase}.real-filters input,.real-filters select{width:100%;padding:10px;border:1px solid var(--line);border-radius:7px;background:#fff}.filter-actions{display:flex;align-items:end;gap:8px}.real-sheet{max-height:65vh;overflow:auto;border:1px solid var(--line);background:#fff}.real-sheet table{min-width:1100px}.real-sheet th{position:sticky;top:0;z-index:2;white-space:nowrap}.real-sheet td{white-space:nowrap}.pagination{display:flex;justify-content:space-between;align-items:center;gap:12px;margin:16px 0}.pagination-links{display:flex;gap:8px}.pagination a,.pagination span{padding:8px 12px;border:1px solid var(--line);border-radius:7px;background:#fff;text-decoration:none}.pagination .disabled{color:var(--muted)}@media(max-width:900px){.real-filters{grid-template-columns:1fr}.real-toolbar{align-items:stretch;flex-direction:column}}
.sync-progress{margin-top:10px;min-width:280px}.sync-progress progress{display:block;width:100%;height:12px;accent-color:var(--turquoise-dark)}.sync-progress span{display:block;margin-top:5px;color:var(--muted);font-size:13px}
.real-import{display:flex;align-items:end;gap:12px;flex-wrap:wrap;margin:14px 0;padding:14px}.real-import label{display:grid;gap:5px;font-size:13px;font-weight:700}.real-import input{padding:8px;border:1px solid var(--line);border-radius:7px;background:#fff}.real-import p{width:100%;margin:0;color:var(--muted);font-size:13px}
.import-progress{flex-basis:100%;display:flex;align-items:center;gap:12px;color:var(--muted);font-size:13px}.import-progress[hidden]{display:none}.import-progress progress{width:min(420px,100%);height:12px;accent-color:var(--turquoise-dark)}
.real-issues{padding:14px;margin:12px 0}.real-issues h2{margin:0 0 8px;font-size:17px}.real-issues table{width:100%;border-collapse:collapse;font-size:13px}.real-issues th,.real-issues td{padding:8px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}.real-issues th{color:var(--turquoise-dark)}.real-issues code{overflow-wrap:anywhere}
</style>
@endpush
@section('content')
<a class="back" href="{{ route('provider-payments.dashboard') }}">← Pago a Proveedores</a><p class="eyebrow">Carga Movimientos Courier</p><h1>Pesos Reales</h1><p class="intro">Consulta y carga los pesos reales por seguimiento, cliente y servicio. Puedes actualizarlos con el botón de esta página; también se sincronizan automáticamente al cargar Bases Courier para procesos abiertos.</p>
@if(session('status'))<div class="status">{{ session('status') }}</div>@endif
@if($errors->has('file'))<div class="status" role="alert">{{ $errors->first('file') }}</div>@endif
@if($importIssues)<section class="card real-issues" role="status"><h2>Incidencias de la última carga @if($importedAt)<small>· {{ $importedAt }}</small>@endif</h2><table><thead><tr><th>Campo</th><th>Dato del archivo</th><th>Qué revisar</th><th>Filas</th><th>Cantidad</th></tr></thead><tbody>@foreach($importIssues as $issue)<tr><td>{{ $issue['field'] }}</td><td><code>{{ $issue['value'] }}</code></td><td>{{ $issue['reason'] }}</td><td>{{ implode(', ', $issue['lines']) }}</td><td>{{ number_format($issue['count'], 0, ',', '.') }}</td></tr>@endforeach</tbody></table>@if($issueOverflow)<p>Hay {{ number_format($issueOverflow, 0, ',', '.') }} incidencias adicionales. Corrige las primeras y vuelve a cargar para revisarlas.</p>@endif</section>@endif
<form class="card real-import" method="post" enctype="multipart/form-data" action="{{ route('provider-payments.maintainers.pesos.reales.import') }}" onsubmit="this.querySelector('button[type=submit]').disabled = true; this.querySelector('.import-progress').hidden = false;">@csrf
<label>Cargar Peso Real desde Excel o CSV (.xlsx, .csv)<input type="file" name="file" accept=".xlsx,.csv" required></label><button type="submit">Cargar planilla</button>
<div class="import-progress" role="status" aria-live="polite" hidden><progress aria-label="Cargando Pesos Reales"></progress><span>Enviando y procesando la planilla. Espera el resultado antes de cerrar esta página.</span></div>
<p>Columnas: Fecha, Seguimiento_Paquete, Codigo_seguimiento, Peso_Real, Cliente, Operario, Observacion, GuiaCliente. En Peso_Real puedes escribir XS (1 kg), S (4), M (6), L (10), XL (30) o XXL (36); los decimales se truncan. Un dato vacío queda sin peso y otro texto aparece en Talla como Error-… para revisión. Los seguimientos repetidos conservan la fila de fecha más reciente; las filas con datos inválidos se omiten y se muestran agrupadas por campo y valor. Se actualizan los seguimientos existentes solo si el período está abierto. Cliente es una referencia: se corrige con Movimientos Courier al cruzar el seguimiento.</p>
</form>
<div class="real-toolbar"><div><h2>Registros de Peso Real</h2><p class="note">La sincronización actualiza Peso Real y recalcula Peso Final. Peso original y Peso Transformado se conservan.</p></div><form method="post" action="{{ route('provider-payments.maintainers.pesos.reales.sync') }}" onsubmit="if (!confirm('¿Confirmas copiar Peso Real y recalcular Peso Final en movimientos_courier?')) return false; this.querySelector('button').disabled = true; this.querySelector('.sync-progress').hidden = false; return true;">@csrf<button type="submit">Copiar Peso Real a movimientos_courier</button><div class="sync-progress" role="status" aria-live="polite" hidden><progress aria-label="Actualizando Peso Real"></progress><span>Actualizando movimientos Courier… espera el resultado.</span></div></form></div>
<form class="card real-filters" method="get">
<label>Año y mes<select name="period"><option value="">Todos</option>@foreach($periods as $option)<option value="{{ $option }}" @selected($option === $period)>{{ $option }}</option>@endforeach</select></label>
<label>Comerciante<select name="merchant"><option value="">Todos</option>@foreach($merchants as $option)<option value="{{ $option }}" @selected($option === $merchant)>{{ $option }}</option>@endforeach</select></label>
<label>Servicio<select name="service"><option value="">Todos</option>@foreach($services as $option)<option value="{{ $option }}" @selected($option === $service)>{{ $option }}</option>@endforeach</select></label>
<label>Buscar<input name="q" value="{{ $search }}" placeholder="Seguimiento, código, comerciante…"></label>
<div class="filter-actions"><button type="submit">Aplicar filtros</button><a class="button" href="{{ route('provider-payments.maintainers.pesos.reales') }}">Limpiar</a></div>
</form>
<p><strong>{{ number_format($rows->total(), 0, ',', '.') }}</strong> registros encontrados. Se muestran 100 por página.</p>
<div class="real-sheet"><table><thead><tr><th>Seguimiento paquete</th><th>Talla</th><th>Peso Real</th><th>Código de seguimiento</th><th>Fecha Proceso</th><th>Cliente de planilla</th><th>Cliente identificado</th><th>Servicio</th><th>Operario</th><th>Observación</th><th>GuíaCliente</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ $row->seguimiento_paquete }}</td><td>{{ $row->talla ?: '—' }}</td><td>{{ $row->peso_real === null ? '—' : number_format($row->peso_real, 0, ',', '.') }}</td><td>{{ $row->codigo_seguimiento }}</td><td>{{ $row->fecha_proceso?->format('d-m-Y') }}</td><td>{{ $row->cliente_origen ?: '—' }}</td><td>{{ $row->servicio ? ($row->comerciante ?: '—') : 'Pendiente de cruce' }}</td><td>{{ $row->servicio ?: 'Pendiente de cruce' }}</td><td>{{ $row->operario ?: '—' }}</td><td>{{ $row->observacion ?: '—' }}</td><td>{{ $row->guia_cliente ?: '—' }}</td></tr>@empty<tr><td colspan="11">No hay registros para los filtros seleccionados.</td></tr>@endforelse</tbody></table></div>
@include('provider-payments::partials.pagination', ['paginator' => $rows])
@endsection
