@extends('provider-payments::layout')
@section('title', 'Peso Real')
@push('styles')<style>.weight-tabs{display:flex;gap:10px;margin:0 0 22px}.weight-tabs a{padding:10px 15px;border:1px solid var(--line);border-radius:8px;background:#fff;text-decoration:none;font-weight:750}.weight-tabs a.active{background:var(--turquoise-dark);color:#fff}.master-grid{display:grid;grid-template-columns:minmax(300px,390px) minmax(520px,1fr);gap:22px;align-items:start}.form-grid{display:grid;gap:16px}.form-grid label{display:grid;gap:7px;font-weight:750}.form-grid input{width:100%;padding:12px;border:1px solid var(--line);border-radius:8px}.status{margin-bottom:18px;padding:14px;border-left:4px solid var(--turquoise-dark);background:#e8fbfa}.badge{display:inline-block;padding:4px 9px;border-radius:99px;background:#e1f7ed;color:#16724a;font-size:12px;font-weight:750}@media(max-width:950px){.master-grid{grid-template-columns:1fr}}</style>@endpush
@section('content')
<a class="back" href="{{ route('provider-payments.dashboard') }}">← Pago a Proveedores</a><p class="eyebrow">Mantenedor de pesos</p><h1>Peso Real</h1><p class="intro">Consulta los pesos recibidos desde el archivo y agrega nuevas equivalencias con su Peso Transformado.</p>
<nav class="weight-tabs"><a href="{{ route('provider-payments.maintainers.pesos.transformados') }}">Peso Transformado</a><a class="active" href="{{ route('provider-payments.maintainers.pesos.reales') }}">Peso Real</a></nav>
@if(session('status'))<div class="status">{{ session('status') }}</div>@endif
<div class="master-grid"><section class="card"><h2>Agregar Peso Real</h2><form class="form-grid" method="post" action="{{ route('provider-payments.maintainers.pesos.reales.store') }}">@csrf
    <label>Peso Real<input name="source_weight" value="{{ old('source_weight') }}" maxlength="100" required placeholder="Ej.: 12.45 kg"></label>
    <label>Peso Transformado<input type="number" name="transformed_weight" value="{{ old('transformed_weight') }}" min="1" step="1" required placeholder="Ej.: 13"></label>
    @if($errors->any())<p class="warning">{{ $errors->first() }}</p>@endif<button type="submit">Agregar Peso Real</button>
</form></section><section class="card"><h2>Pesos Reales registrados <span class="note">({{ number_format($weights->count(), 0, ',', '.') }})</span></h2><div class="table-wrap"><table><thead><tr><th>Peso Real</th><th>Peso Transformado</th><th>Estado</th></tr></thead><tbody>@forelse($weights as $weight)<tr><td>{{ $weight->source_weight }}</td><td>{{ $weight->transformed_weight }}</td><td><span class="badge">{{ $weight->is_active ? 'Activo' : 'Inactivo' }}</span></td></tr>@empty<tr><td colspan="3">No hay Pesos Reales registrados.</td></tr>@endforelse</tbody></table></div></section></div>
@endsection
