<div class="maintenance-form-grid">
    <label>Tipo de mantención<input type="text" name="maintenance_type" maxlength="100" required value="{{ old('maintenance_type', $maintenance?->maintenance_type) }}" placeholder="Ej.: preventiva, cambio de aceite"></label>
    <label>Tipo de ejecución<select name="execution_type" required><option value="internal" @selected(old('execution_type', $maintenance?->execution_type ?? 'internal') === 'internal')>Interna</option><option value="external" @selected(old('execution_type', $maintenance?->execution_type) === 'external')>Externa</option></select></label>
    <label>Estado<select name="status"><option value="pending" @selected(old('status', $maintenance?->status ?? 'pending') === 'pending')>Pendiente</option><option value="scheduled" @selected(old('status', $maintenance?->status) === 'scheduled')>Agendada</option>@if($maintenance?->status === 'scheduled' || $maintenance?->status === 'in_progress')<option value="in_progress" @selected(old('status', $maintenance?->status) === 'in_progress')>En mantención</option>@endif@if($maintenance)<option value="cancelled">Cancelada</option>@endif</select></label>
    <label>Fecha prevista<input type="datetime-local" name="scheduled_at" value="{{ old('scheduled_at', $maintenance?->scheduled_at?->format('Y-m-d\TH:i')) }}"></label>
    <label>Kilometraje informado<input type="number" name="reported_odometer_km" min="0" value="{{ old('reported_odometer_km', $maintenance?->reported_odometer_km) }}"></label>
    <label>Proveedor previsto<select name="provider_id"><option value="">Sin asignar / ejecución interna</option>@foreach($providers as $provider)<option value="{{ $provider->id }}" @selected((string) old('provider_id', $maintenance?->provider_id) === (string) $provider->id)>{{ $provider->operational_name ?: $provider->legal_name }}</option>@endforeach</select></label>
    <label>Costo estimado ($)<input type="number" name="estimated_cost" min="0" step="0.01" value="{{ old('estimated_cost', $maintenance?->estimated_cost) }}"></label>
    <label>Responsable interno<select name="responsible_user_id"><option value="">Sin asignar</option>@foreach($responsibles as $user)<option value="{{ $user->id }}" @selected((string) old('responsible_user_id', $maintenance?->responsible_user_id) === (string) $user->id)>{{ $user->name }}</option>@endforeach</select></label>
    <label>Próxima mantención por fecha<input type="date" name="next_due_at" value="{{ old('next_due_at', $maintenance?->next_due_at?->format('Y-m-d')) }}"></label>
    <label>Próxima mantención por kilometraje<input type="number" name="next_due_km" min="0" value="{{ old('next_due_km', $maintenance?->next_due_km) }}"></label>
    <label class="wide">Observaciones<textarea name="notes" rows="3">{{ old('notes', $maintenance?->notes) }}</textarea></label>
    @if($maintenance)<label class="wide">Motivo de cambio/cancelación<input type="text" name="change_reason" maxlength="2000" value="{{ old('change_reason') }}" placeholder="Obligatorio si cancelas"></label>@endif
</div>
